@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="mb-0">Dashboard</h1><div class="text-muted">A clear view of your accounting position</div></div></div>
@if(!$company)<div class="card p-4"><h5>Welcome to {{ config('app.name') }}</h5><p>Create your first accounting entity to begin.</p><a class="btn btn-primary align-self-start" href="{{ route('companies.create') }}">Create Accounting Entity</a></div>@else
<form class="card card-body mb-3" method="get" id="dashboard-context"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Accounting Entity</label><select class="form-select" name="company_id" onchange="switchDashboardEntity(this.form)">@foreach($companies as $item)<option value="{{ $item->id }}" @selected($item->id===$company->id)>{{ $item->entity_label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Financial Year</label><select class="form-select" name="financial_year_id" onchange="this.form.submit()"><option value="" @selected(!$financialYear)>No current Financial Year configured</option>@foreach($financialYears as $year)<option value="{{ $year->id }}" @selected($financialYear?->id===$year->id)>{{ $year->name }} ({{ ucfirst($year->status) }})</option>@endforeach</select></div>@if($supportsBranches)<div class="col-md-4"><label class="form-label">Branch</label><select class="form-select" name="branch_id" onchange="this.form.submit()"><option value="">All branches (consolidated)</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branch->id===$branchId)>{{ $branch->code }} — {{ $branch->name }}</option>@endforeach</select></div>@else<div class="col-md-4"><label class="form-label">Branch</label><div class="form-control bg-light text-muted" aria-label="Branch not applicable">Not applicable</div></div>@endif</div></form>
<div class="mb-3"><strong>{{ $company->entity_label }}</strong><span class="text-muted ms-2">{{ $financialYear ? $financialYear->starts_on->format('d M Y').' – '.$financialYear->ends_on->format('d M Y') : 'No current Financial Year configured.' }} · {{ $period ? $period->name : 'No current period' }}</span></div>
<div class="row g-3 mb-4">@foreach(['Cash / Bank'=>'cash','Accounts Receivable'=>'receivables','Sales This Month'=>'sales','Expenses This Month'=>'expenses','Net Profit / Loss'=>'profit'] as $label=>$key)<div class="col-md-6 col-xl"><div class="card h-100 p-3"><div class="text-muted">{{ $label }}</div><div class="fs-3 fw-semibold">{{ $money->format($metrics[$key], $company->baseCurrency) }}</div></div></div>@endforeach</div>
<div class="row g-3"><div class="col-lg-8"><div class="card"><div class="card-header fw-semibold">Recent Activity</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Status</th></tr></thead><tbody>@forelse($metrics['activity'] as $row)<tr><td>{{ \Carbon\Carbon::parse($row['date'])->format('d M Y') }}</td><td>{{ $row['type'] }}</td><td>{{ $row['reference'] }}</td><td>{{ ucfirst(str_replace('_',' ',$row['status'])) }}</td></tr>@empty<tr><td colspan="4" class="text-muted">No accounting activity yet.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-4"><div class="card p-3 mb-3"><h5>Receivables</h5><div>Open invoices <strong class="float-end">{{ $metrics['open_invoices'] }}</strong></div><div>Overdue <strong class="float-end text-danger">{{ $metrics['overdue_invoices'] }}</strong></div></div>@if($supportsBranches)<div class="card p-3"><h5>Quick Actions</h5><div class="d-grid gap-2"><a class="btn btn-primary" href="{{ route('journals.create', $company) }}">New Journal</a><a class="btn btn-outline-primary" href="{{ route('sales.customers', $company) }}">Customers</a><a class="btn btn-outline-primary" href="{{ route('sales.items', $company) }}">Products & Services</a><a class="btn btn-outline-secondary" href="{{ route('companies.branches.index', $company) }}">Manage Branches</a></div></div>@endif</div></div>
<script>function switchDashboardEntity(form){const year=form.querySelector('[name="financial_year_id"]'),branch=form.querySelector('[name="branch_id"]');if(year)year.value='';if(branch)branch.value='';form.submit()}</script>
@endif
@endsection
