@extends('layouts.app')
@section('content')
<nav class="mb-3"><a href="{{ route('period-end') }}">Period-End</a> &gt; {{ $company->country->name }} &gt; <a href="{{ route('period-end.entity', [$company->country->code, $company]) }}">{{ $company->entity_label }}</a> &gt; {{ $year->name }} &gt; {{ $period->name }}</nav>
<h1>Period-End — {{ $period->name }}</h1>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card p-3"><strong>Period Status</strong><span>{{ ucfirst($period->status) }}</span></div></div><div class="col-md-3"><div class="card p-3"><strong>FY Status</strong><span>{{ ucfirst($year->status) }}</span></div></div><div class="col-md-3"><div class="card p-3"><strong>AR / AP Review</strong><span>{{ $ar }} / {{ $ap }}</span></div></div><div class="col-md-3"><div class="card p-3"><strong>Closing Readiness</strong><span>{{ $summary['ready'] ? 'Ready' : count($summary['blockers']).' blocker(s)' }}</span></div></div></div>
@if(bccomp($suspenseBalance,'0',4)!==0)<div class="alert alert-warning">Suspense account balance is {{ $suspenseBalance }}. Review it; no automatic clearing entry will be created.</div>@endif
@unless($summary['ready'])<div class="alert alert-warning"><strong>Closing blockers</strong><ul class="mb-0">@foreach($summary['blockers'] as $blocker)<li>{{ $blocker }}</li>@endforeach</ul></div>@endunless
<div class="card p-3 mb-4"><h3>Closing Checklist</h3>@foreach($period->checklistItems as $item)<div class="border-top py-2"><div class="d-flex justify-content-between"><span>{{ $item->label }} @if($item->is_system_check)<span class="badge text-bg-info">System check</span>@endif</span><strong>{{ $item->is_system_check ? (collect($summary['blockers'])->contains(fn($b) => str_contains(strtolower($b), str($item->key)->replace('_',' '))) ? 'Blocked' : 'Passed') : ucfirst(str_replace('_',' ',$item->status)) }}</strong></div>@unless($item->is_system_check)<form class="row g-2 mt-1" method="post" action="{{ route('period-end.checklist.update', [$company->country->code,$company,$year,$period,$item]) }}">@csrf @method('PATCH')<div class="col-md-3"><select class="form-select" name="status">@foreach(['not_started','in_progress','completed','not_applicable'] as $status)<option value="{{ $status }}" @selected($item->status===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></div><div class="col-md-7"><input class="form-control" name="notes" value="{{ $item->notes }}" placeholder="Review notes"></div><div class="col-md-2"><button class="btn btn-outline-primary">Update</button></div></form>@endunless</div>@endforeach</div>
<div class="card p-3 mb-4"><h3>Accountant Adjustment</h3><form method="post" action="{{ route('period-end.adjustments.store', [$company->country->code,$company,$year,$period]) }}">@csrf<div class="row g-2"><div class="col-md-3"><label class="form-label">Adjustment Date</label><input class="form-control" type="date" name="transaction_date" value="{{ $period->ends_on->toDateString() }}" required></div><div class="col-md-3"><label class="form-label">Reference</label><input class="form-control" name="reference"></div><div class="col-md-3"><label class="form-label">Description</label><input class="form-control" name="description" required></div><div class="col-md-3"><label class="form-label">Scheduled Reversal Date</label><input class="form-control" type="date" name="reversal_date"></div><div class="col-12"><label class="form-label">Reason / Explanation</label><textarea class="form-control" name="reason" required></textarea></div>@if($company->supportsBranches())<div class="col-md-4"><label class="form-label">Branch</label><select class="form-select" name="branch_id">@foreach($company->branches()->where('is_active',true)->get() as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div>@endif</div><table class="table mt-3"><thead><tr><th>Account</th><th>Line Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody>@for($i=0;$i<2;$i++)<tr><td><select class="form-select" name="lines[{{$i}}][account_id]">@foreach($accounts as $account)<option value="{{$account->id}}">{{$account->code}} — {{$account->name}}</option>@endforeach</select></td><td><input class="form-control" name="lines[{{$i}}][description]" required></td><td><input class="form-control" inputmode="decimal" name="lines[{{$i}}][debit]" value="0" required></td><td><input class="form-control" inputmode="decimal" name="lines[{{$i}}][credit]" value="0" required></td></tr>@endfor</tbody></table><label class="form-check"><input class="form-check-input" type="checkbox" name="post_now" value="1"> Post immediately</label><button class="btn btn-primary mt-3">Create Adjustment</button></form></div>
<div class="card p-3 mb-4"><h3>Bank Reconciliation Review</h3>@forelse($bankReview as $bank)<div>{{ $bank->name }} — {{ optional($bank->reconciliations->first())->statement_end_date?->format('d M Y') ?? 'No completed reconciliation' }}</div>@empty<p class="text-muted">No Bank accounts. Cash accounts do not require reconciliation.</p>@endforelse</div>
<div class="card p-3 mb-4"><div class="d-flex justify-content-between"><div><h3>Prior-Period Adjustments</h3><p class="mb-0">{{ $priorAdjustments->count() }} adjustment record(s) posting into this Financial Year.</p></div><a class="btn btn-outline-primary align-self-start" href="{{ route('companies.prior-adjustments.create',$company) }}">Create Prior-Period Adjustment</a></div></div>
<div class="card p-3 mb-4"><h3>Lock Controls</h3><form class="row g-2" method="post" action="{{ route('period-end.locks',[$company->country->code,$company]) }}">@csrf @method('PATCH')<div class="col-md-4"><label class="form-label">Bookkeeping Lock Date</label><input class="form-control" type="date" name="bookkeeping_lock_date" value="{{ $company->bookkeeping_lock_date?->toDateString() }}"></div><div class="col-md-4"><label class="form-label">Adviser Lock Date</label><input class="form-control" type="date" name="adviser_lock_date" value="{{ $company->adviser_lock_date?->toDateString() }}"></div><div class="col-md-4 align-self-end"><button class="btn btn-outline-primary">Update Locks</button></div></form></div>
@if($period->status==='open')<form method="post" action="{{ route('period-end.period.close',[$company->country->code,$company,$year,$period]) }}">@csrf<label class="form-label">Close reason</label><input class="form-control mb-2" name="reason" minlength="10" required><button class="btn btn-danger" @disabled(!$summary['ready'])>Close Period</button></form>@else<form method="post" action="{{ route('period-end.period.reopen',[$company->country->code,$company,$year,$period]) }}">@csrf<label class="form-label">Reopen reason</label><input class="form-control mb-2" name="reason" minlength="10" required><button class="btn btn-warning">Reopen Period</button></form>@endif
@endsection
