@extends('layouts.app')
@section('title', 'Accounting Entity Import')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('import-export') }}">Import & Export</a></li><li class="breadcrumb-item"><a href="{{ route('import-export.country', $country->code) }}">{{ $country->name }}</a></li><li class="breadcrumb-item active">Entity Import #{{ $batch->id }}</li></ol></nav>
<h1>Import New Accounting Entity</h1><p class="text-muted">{{ $country->name }} · {{ $batch->original_filename }} · {{ str($batch->status)->title() }}</p>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($batch->status === 'uploaded')<div class="card card-body"><h2 class="h5">Select Worksheet</h2><form method="post" action="{{ route('import-export.entity-imports.worksheet', [$country->code, $batch]) }}">@csrf<select class="form-select" name="worksheet" required><option value="">Choose worksheet</option>@foreach($batch->mapped_values['worksheets'] ?? [] as $sheet)<option>{{ $sheet }}</option>@endforeach</select><button class="btn btn-primary mt-3">Continue</button></form></div>@endif
@if($batch->status === 'mapping' || $batch->status === 'ready')<div class="card card-body mb-4"><h2 class="h5">Map Fields</h2><p class="text-muted">Source Column → Arua Entity Field. Fields marked * are required.</p><form method="post" action="{{ route('import-export.entity-imports.validate', [$country->code, $batch]) }}">@csrf<div class="row g-3">@foreach($batch->source_headers as $header)<div class="col-md-6"><label class="form-label">{{ $header }}</label><select class="form-select" name="mapping[{{ $header }}]"><option value="">Ignore column</option>@foreach($fields as $key => $field)<option value="{{ $key }}" @selected(($batch->mapping[$header] ?? null) === $key)>{{ $field['label'] }}{{ $field['required'] ? ' *' : '' }}</option>@endforeach</select></div>@endforeach</div><button class="btn btn-primary mt-3">Validate and Preview</button></form></div>@endif
@if($batch->mapped_values && $batch->status !== 'uploaded')<div class="card mb-4"><div class="card-header fw-semibold">Entity Preview</div><div class="card-body"><dl class="row mb-0">@foreach(['country' => 'Country', 'entity_name' => 'Entity Name', 'entity_type' => 'Entity Type', 'base_currency' => 'Base Currency', 'timezone' => 'Timezone', 'financial_year_start' => 'Financial Year Start', 'financial_year_end' => 'Financial Year End', 'legal_name' => 'Legal Name', 'email' => 'Email', 'phone' => 'Phone'] as $key => $label)<dt class="col-sm-4">{{ $label }}</dt><dd class="col-sm-8">{{ $key === 'country' ? $country->name : ($batch->mapped_values[$key] ?? '—') }}</dd>@endforeach<dt class="col-sm-4">Status</dt><dd class="col-sm-8">@if($batch->errors)<span class="badge text-bg-danger">ERROR</span>@elseif($batch->duplicate_status === 'possible_duplicate')<span class="badge text-bg-warning">POSSIBLE DUPLICATE</span>@else<span class="badge text-bg-success">VALID</span>@endif</dd></dl>@foreach($batch->warnings as $warning)<div class="alert alert-warning">{{ $warning }}</div>@endforeach @foreach($batch->errors as $error)<div class="alert alert-danger">{{ $error }}</div>@endforeach</div></div>@endif
@if($batch->status === 'ready')<form method="post" action="{{ route('import-export.entity-imports.confirm', [$country->code, $batch]) }}" onsubmit="return confirm('Create this Accounting Entity using the validated preview?')">@csrf<button class="btn btn-success">Confirm and Create Accounting Entity</button></form>@endif
@if($batch->status === 'completed' && $batch->resultCompany)<div class="card card-body border-success"><h2 class="h5">Accounting Entity successfully imported.</h2><p>{{ $batch->resultCompany->entity_label }} is now available in normal Arua workflows.</p><div class="d-flex flex-wrap gap-2"><a class="btn btn-primary" href="{{ route('companies.show', $batch->resultCompany) }}">Open Accounting Entity</a><a class="btn btn-outline-primary" href="{{ route('import-export.workspace', [$country->code, $batch->resultCompany]) }}">Import Data Into This Entity</a><a class="btn btn-outline-secondary" href="{{ route('import-export.entity-imports.create', $country->code) }}">Import Another Accounting Entity</a><a class="btn btn-outline-secondary" href="{{ route('import-export') }}">Return to Import & Export</a></div><hr><strong>Next setup steps</strong><ul class="mb-0"><li>Review the created Financial Year and periods.</li>@if($batch->resultCompany->supportsBranches())<li>Create additional branches where required (Head Office was created by the standard workflow).</li>@endif<li>Configure tax if needed.</li><li>Import Chart of Accounts, customers, suppliers, products, and transactions through the entity workspace.</li></ul></div>@endif
@endsection
