@extends('layouts.app')
@section('title', 'Accounting Entity Import')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('import-export') }}">Import & Export</a></li><li class="breadcrumb-item"><a href="{{ route('import-export.country', $country->code) }}">{{ $country->name }}</a></li><li class="breadcrumb-item active">Entity Import #{{ $batch->id }}</li></ol></nav>
<h1>Import New Accounting Entity</h1><p class="text-muted">{{ $country->name }} · {{ $batch->original_filename }} · {{ str($batch->status)->title() }}</p>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($batch->status === 'uploaded')<div class="card card-body"><h2 class="h5">Select Worksheet</h2><form method="post" action="{{ route('import-export.entity-imports.worksheet', [$country->code, $batch]) }}">@csrf<select class="form-select" name="worksheet" required><option value="">Choose worksheet</option>@foreach($batch->mapped_values['worksheets'] ?? [] as $sheet)<option>{{ $sheet }}</option>@endforeach</select><button class="btn btn-primary mt-3">Continue</button></form></div>@endif
@if($batch->status === 'mapping' || request()->boolean('change_mapping'))<div class="card card-body mb-4"><h2 class="h5">Column Mapping</h2><p class="text-muted">Match each source column to an Arua field. Sample values confirm that the file data was read correctly.</p><form method="post" action="{{ route('import-export.entity-imports.validate', [$country->code, $batch]) }}">@csrf<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Source Column</th><th>Sample Value</th><th>Arua Field</th></tr></thead><tbody>@foreach($batch->source_headers as $header)<tr><td>{{ $header }}</td><td>{{ $batch->raw_values[$header] ?? '—' }}</td><td><select class="form-select" name="mapping[{{ $header }}]"><option value="">Ignore column</option>@foreach($fields as $key => $field)<option value="{{ $key }}" @selected(($batch->mapping[$header] ?? null) === $key)>{{ $field['label'] }}{{ $field['required'] ? ' *' : '' }}</option>@endforeach</select></td></tr>@endforeach</tbody></table></div><button class="btn btn-primary">Validate and Preview</button></form></div>@endif
@if($batch->mapped_values && $batch->status !== 'uploaded')<div class="card mb-4"><div class="card-header fw-semibold">Accounting Entity Preview</div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">Entity Name</dt><dd class="col-sm-8">{{ $batch->mapped_values['entity_name'] ?? '—' }}</dd><dt class="col-sm-4">Entity Type</dt><dd class="col-sm-8">{{ str($batch->mapped_values['entity_type'] ?? '')->replace('_', ' ')->title() }}</dd><dt class="col-sm-4">Legal Name</dt><dd class="col-sm-8">{{ $batch->mapped_values['legal_name'] ?? '—' }}</dd><dt class="col-sm-4">Country / Jurisdiction</dt><dd class="col-sm-8">{{ $country->name }}</dd><dt class="col-sm-4">Base Currency</dt><dd class="col-sm-8">{{ $batch->mapped_values['base_currency'] ?? '—' }}</dd><dt class="col-sm-4">Timezone</dt><dd class="col-sm-8">{{ $batch->mapped_values['timezone'] ?? '—' }}</dd><dt class="col-sm-4">Financial Year</dt><dd class="col-sm-8">{{ filled($batch->mapped_values['financial_year_start'] ?? null) ? \Illuminate\Support\Carbon::parse($batch->mapped_values['financial_year_start'])->format('d-M-Y') : '—' }} to {{ filled($batch->mapped_values['financial_year_end'] ?? null) ? \Illuminate\Support\Carbon::parse($batch->mapped_values['financial_year_end'])->format('d-M-Y') : '—' }}</dd>@foreach(['address' => 'Address', 'email' => 'Email', 'phone' => 'Phone'] as $key => $label)<dt class="col-sm-4">{{ $label }}</dt><dd class="col-sm-8">{{ $batch->mapped_values[$key] ?? '—' }}</dd>@endforeach<dt class="col-sm-4">Status</dt><dd class="col-sm-8">@if($batch->errors)<span class="badge text-bg-danger">ERROR</span>@elseif($batch->duplicate_status === 'possible_duplicate')<span class="badge text-bg-warning">POSSIBLE DUPLICATE</span>@else<span class="badge text-bg-success">VALID</span>@endif</dd></dl>@foreach($batch->warnings as $warning)<div class="alert alert-warning">{{ $warning }}</div>@endforeach @foreach($batch->errors as $error)<div class="alert alert-danger">{{ $error }}</div>@endforeach</div></div>@endif
@if($batch->status === 'ready')<div class="d-flex flex-wrap gap-2"><form method="post" action="{{ route('import-export.entity-imports.confirm', [$country->code, $batch]) }}" onsubmit="return confirm('Create this Accounting Entity using the validated preview?')">@csrf<button class="btn btn-success">Confirm Import</button></form><a class="btn btn-outline-primary" href="{{ route('import-export.entity-imports.show', [$country->code, $batch, 'change_mapping' => 1]) }}">Change Mapping</a><a class="btn btn-outline-secondary" href="{{ route('import-export.country', $country->code) }}">Cancel</a></div>@endif
@if($batch->status === 'completed' && $batch->resultCompany)<div class="card card-body border-success"><h2 class="h5">Accounting Entity successfully imported.</h2><p>{{ $batch->resultCompany->entity_label }} is now available in normal Arua workflows.</p><div class="d-flex flex-wrap gap-2"><a class="btn btn-primary" href="{{ route('companies.show', $batch->resultCompany) }}">Open Accounting Entity</a><a class="btn btn-outline-primary" href="{{ route('import-export.workspace', [$country->code, $batch->resultCompany]) }}">Import Data Into This Entity</a><a class="btn btn-outline-secondary" href="{{ route('import-export.entity-imports.create', $country->code) }}">Import Another Accounting Entity</a><a class="btn btn-outline-secondary" href="{{ route('import-export') }}">Return to Import & Export</a></div><hr><strong>Next setup steps</strong><ul class="mb-0"><li>Review the created Financial Year and periods.</li>@if($batch->resultCompany->supportsBranches())<li>Create additional branches where required (Head Office was created by the standard workflow).</li>@endif<li>Configure tax if needed.</li><li>Import Chart of Accounts, customers, suppliers, products, and transactions through the entity workspace.</li></ul></div>@endif
@endsection
