@extends('layouts.app')
@section('title', 'Undo Import')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('import-export.workspace', [$company->country->code, $company]) }}">Import & Export</a></li><li class="breadcrumb-item"><a href="{{ route('import-export.batches.show', [$company->country->code, $company, $batch]) }}">Batch #{{ $batch->id }}</a></li><li class="breadcrumb-item active">Undo Import</li></ol></nav>
<h1>Undo {{ str($batch->data_type)->replace('_', ' ')->title() }} Import #{{ $batch->id }}</h1>
<div class="alert alert-warning">Draft records may be removed. Posted accounting records will be reversed only where Arua's accounting controls permit. Historical posted records are never directly deleted.</div>
<div class="card mb-4"><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">Country / Jurisdiction</dt><dd class="col-sm-8">{{ $company->country->name }}</dd><dt class="col-sm-4">Accounting Entity</dt><dd class="col-sm-8">{{ $company->entity_label }}</dd><dt class="col-sm-4">Import Batch</dt><dd class="col-sm-8">#{{ $batch->id }}</dd><dt class="col-sm-4">Filename</dt><dd class="col-sm-8">{{ $batch->original_filename }}</dd><dt class="col-sm-4">Import Type</dt><dd class="col-sm-8">{{ str($batch->data_type)->replace('_', ' ')->title() }}</dd><dt class="col-sm-4">Imported By</dt><dd class="col-sm-8">{{ $batch->uploader?->name }}</dd><dt class="col-sm-4">Imported</dt><dd class="col-sm-8">{{ $batch->confirmed_at ?? $batch->uploaded_at }}</dd><dt class="col-sm-4">Rows / Documents</dt><dd class="col-sm-8">{{ $batch->total_rows }} / {{ $batch->documentCount() ?? $batch->imported_rows }}</dd><dt class="col-sm-4">Created / Already removed</dt><dd class="col-sm-8">{{ $analysis['created_records'] }} / {{ $analysis['already_undone'] }}</dd><dt class="col-sm-4">Safe / Reversal / Blocked</dt><dd class="col-sm-8">{{ $analysis['safe'] }} / {{ $analysis['reversal'] }} / {{ $analysis['blocked'] }}</dd><dt class="col-sm-4">Affected journals / tax records</dt><dd class="col-sm-8">{{ $analysis['affected_journals'] }} / {{ $analysis['affected_tax_records'] }}</dd></dl></div></div>
<div class="card mb-4"><div class="card-header fw-semibold">Preflight analysis</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Classification</th><th>Record</th><th>Result</th></tr></thead><tbody>@forelse($analysis['entries'] as $entry)<tr><td><span class="badge {{ $entry['classification'] === 'BLOCKED' ? 'text-bg-danger' : ($entry['classification'] === 'REVERSAL_REQUIRED' ? 'text-bg-warning' : 'text-bg-success') }}">{{ $entry['classification'] }}</span></td><td>{{ $entry['type'] }}{{ $entry['id'] ? ' #'.$entry['id'] : '' }}</td><td>{{ $entry['reason'] }}</td></tr>@empty<tr><td colspan="3" class="text-muted">This batch created no records.</td></tr>@endforelse</tbody></table></div></div>
@if($analysis['blocked'])<div class="alert alert-danger">This batch cannot be undone atomically. Resolve every blocked dependency first. No records have been changed.</div>@elseif($batch->undo_status === 'undone')<div class="alert alert-success">This import has already been undone.</div>@else<form method="post" action="{{ route('import-export.batches.undo', [$company->country->code, $company, $batch]) }}" class="card card-body">@csrf @if($analysis['reversal'])<div class="mb-3"><label class="form-label">Reversal Date</label><input type="date" name="reversal_date" class="form-control" required></div>@endif<div class="form-check mb-3"><input class="form-check-input" type="checkbox" value="1" name="understood" id="understood" required><label class="form-check-label" for="understood">I understand that this operation will undo records created by this import.</label></div><div class="mb-3"><label class="form-label">Type UNDO to confirm</label><input class="form-control" name="confirmation" pattern="UNDO" autocomplete="off" required></div><div class="d-flex gap-2"><button class="btn btn-danger">Undo Import</button><a class="btn btn-outline-secondary" href="{{ route('import-export.batches.show', [$company->country->code, $company, $batch]) }}">Cancel</a></div></form>@endif
@endsection
