@extends('layouts.app')
@section('title', 'Import & Export Workspace')
@section('content')
<nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('import-export') }}">Import & Export</a></li><li class="breadcrumb-item"><a href="{{ route('import-export.country', $company->country->code) }}">{{ $company->country->name }}</a></li><li class="breadcrumb-item active">{{ $company->entity_label }}</li></ol></nav>
<div class="mb-4"><h1>{{ $company->entity_label }} – Import & Export</h1><div class="text-muted">{{ $company->country->name }} · {{ str($company->entity_type)->replace('_', ' ')->title() }} · {{ $company->supportsBranches() ? 'Branch-aware' : 'Branch: Not applicable' }}</div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<h2 class="h4">Import</h2>
<div class="row g-3 mb-4">
    <div class="col-md-4"><div class="card h-100 border-primary"><div class="card-body"><h3 class="h5">New Import</h3><p class="text-muted">Upload CSV or XLSX, preview the data, then confirm.</p><a class="btn btn-primary" href="{{ route('import-export.imports.create', [$company->country->code, $company]) }}">Start New Import</a></div></div></div>
    <div class="col-md-4"><div class="card h-100"><div class="card-body"><h3 class="h5">Import History</h3><p class="text-muted">Review uploaded, validated, completed, failed, or cancelled batches.</p><a class="btn btn-outline-primary" href="#import-history">View Import History</a></div></div></div>
    <div class="col-md-4"><div class="card h-100"><div class="card-body"><h3 class="h5">Import Profiles</h3><p class="text-muted">Create and reuse entity-scoped column mappings.</p><a class="btn btn-outline-primary" href="#import-profiles">View Import Profiles</a></div></div></div>
</div>

<div class="card mb-4"><div class="card-header fw-semibold">Supported Imports</div><div class="card-body"><div class="row g-2">@foreach($importTypes as $key => $label)<div class="col-sm-6 col-lg-3"><a class="btn btn-outline-secondary w-100 text-start" href="{{ route('import-export.imports.create', [$company->country->code, $company, 'data_type' => $key]) }}">{{ $label }}</a></div>@endforeach</div><hr><p class="mb-2"><strong>Bank Statement Evidence</strong> uses the existing Banking statement workflow and never creates journals by upload alone.</p><a class="btn btn-outline-secondary" href="{{ route('banking.accounts', [$company->country->code, $company]) }}">Open Banking Accounts</a><p class="form-text mb-0">Customer Receipts and Supplier Payments are not direct import types.</p></div></div>

<h2 class="h4">Export</h2><div class="card mb-4"><div class="card-body d-flex flex-wrap justify-content-between gap-3 align-items-center"><div><h3 class="h5 mb-1">New Export</h3><span class="text-muted">Download entity data as CSV or XLSX.</span></div><a class="btn btn-primary" href="{{ route('import-export.exports.create', [$company->country->code, $company]) }}">New Export</a></div></div>

<div id="import-history" class="card mb-4"><div class="card-header fw-semibold">Import History</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Filename</th><th>Data Type</th><th>Status</th><th>Total</th><th>Imported</th><th>Failed</th><th>Duplicates</th><th>User</th></tr></thead><tbody>@forelse($batches as $batch)<tr><td>{{ $batch->uploaded_at }}</td><td><a href="{{ route('import-export.batches.show', [$company->country->code, $company, $batch]) }}">{{ $batch->original_filename }}</a></td><td>{{ $importTypes[$batch->data_type] ?? $batch->data_type }}</td><td>{{ $batch->statusLabel() }}</td><td>{{ $batch->total_rows }}</td><td>{{ $batch->imported_rows }}</td><td>{{ $batch->invalid_rows + $batch->failed_rows }}</td><td>{{ $batch->duplicate_rows }}</td><td>{{ $batch->uploader?->name }}</td></tr>@empty<tr><td colspan="9" class="text-muted">No imports yet.</td></tr>@endforelse</tbody></table></div></div>

<div class="row g-4"><div class="col-lg-6"><div id="import-profiles" class="card h-100"><div class="card-header fw-semibold d-flex justify-content-between align-items-center"><span>Import Profiles</span><a class="btn btn-sm btn-outline-primary" href="{{ route('import-export.profiles.create', [$company->country->code, $company]) }}">Create Profile</a></div><div class="list-group list-group-flush">@forelse($profiles as $profile)<a class="list-group-item list-group-item-action" href="{{ route('import-export.profiles.edit', [$company->country->code, $company, $profile]) }}">{{ $profile->name }}<small class="d-block text-muted">{{ $importTypes[$profile->data_type] ?? $profile->data_type }}</small></a>@empty<div class="list-group-item text-muted">No saved profiles.</div>@endforelse</div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header fw-semibold">Export History</div><div class="list-group list-group-flush">@forelse($exports as $export)<div class="list-group-item"><strong>{{ $exportTypes[$export->data_type] ?? $export->data_type }}</strong><small class="d-block text-muted">{{ $export->filename }} · {{ strtoupper($export->format) }} · {{ $export->row_count }} rows · {{ $export->generated_at }}</small></div>@empty<div class="list-group-item text-muted">No exports yet.</div>@endforelse</div></div></div></div>
@endsection
