<?php

use App\Http\Controllers\Accounting\JournalController;
use App\Http\Controllers\Accounting\ReportController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\BankingController;
use App\Http\Controllers\Company\BranchController;
use App\Http\Controllers\Company\CompanyController;
use App\Http\Controllers\Company\FinancialYearController;
use App\Http\Controllers\Company\PriorPeriodAdjustmentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PeriodEndController;
use App\Http\Controllers\Purchases\PurchasesController;
use App\Http\Controllers\Sales\ReceivablesController;
use App\Http\Controllers\Sales\SalesController;
use App\Http\Controllers\Sales\SalesTransactionController;
use App\Http\Controllers\TaxController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);
});
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::resource('companies', CompanyController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update']);
    Route::get('/accounting-entities/country/{country}', [CompanyController::class, 'country'])->name('companies.country');
    Route::get('/accounting-entities/country/{country}/create', [CompanyController::class, 'createInCountry'])->name('companies.country.create');
    Route::post('/accounting-entities/country/{country}', [CompanyController::class, 'storeInCountry'])->name('companies.country.store');
    Route::patch('/companies/{company}/status', [CompanyController::class, 'status'])->name('companies.status');
    Route::get('/companies/{company}/delete', [CompanyController::class, 'confirmDelete'])->name('companies.delete');
    Route::delete('/companies/{company}', [CompanyController::class, 'destroy'])->name('companies.destroy');
    Route::get('/companies/{company}/financial-years', [FinancialYearController::class, 'index'])->name('companies.financial-years.index');
    Route::post('/companies/{company}/financial-years', [FinancialYearController::class, 'store'])->name('companies.financial-years.store');
    Route::post('/companies/{company}/financial-years/{financialYear}/begin-closing', [FinancialYearController::class, 'beginClosing'])->name('companies.financial-years.begin-closing');
    Route::post('/companies/{company}/financial-years/{financialYear}/cancel-closing', [FinancialYearController::class, 'cancelClosing'])->name('companies.financial-years.cancel-closing');
    Route::post('/companies/{company}/financial-years/{financialYear}/close', [FinancialYearController::class, 'close'])->name('companies.financial-years.close');
    Route::post('/companies/{company}/financial-years/{financialYear}/reopen', [FinancialYearController::class, 'reopen'])->name('companies.financial-years.reopen');
    Route::post('/companies/{company}/financial-years/{financialYear}/file', [FinancialYearController::class, 'markFiled'])->name('companies.financial-years.file');
    Route::post('/companies/{company}/financial-years/{financialYear}/periods/{period}/close', [FinancialYearController::class, 'closePeriod'])->name('companies.financial-years.periods.close');
    Route::post('/companies/{company}/financial-years/{financialYear}/periods/{period}/reopen', [FinancialYearController::class, 'reopenPeriod'])->name('companies.financial-years.periods.reopen');
    Route::get('/companies/{company}/prior-period-adjustments/create', [PriorPeriodAdjustmentController::class, 'create'])->name('companies.prior-adjustments.create');
    Route::post('/companies/{company}/prior-period-adjustments', [PriorPeriodAdjustmentController::class, 'store'])->name('companies.prior-adjustments.store');
    Route::resource('/companies/{company}/branches', BranchController::class)->except(['show'])->names([
        'index' => 'companies.branches.index',
        'create' => 'companies.branches.create',
        'store' => 'companies.branches.store',
        'edit' => 'companies.branches.edit',
        'update' => 'companies.branches.update',
        'destroy' => 'companies.branches.destroy',
    ]);
    Route::patch('/companies/{company}/branches/{branch}/status', [BranchController::class, 'status'])->name('companies.branches.status');
    Route::get('/accounting', [JournalController::class, 'index'])->name('accounting');
    Route::get('/companies/{company}/journals/create', [JournalController::class, 'create'])->name('journals.create');
    Route::post('/companies/{company}/journals', [JournalController::class, 'store'])->name('journals.store');
    Route::get('/companies/{company}/journals/{journal}', [JournalController::class, 'show'])->name('journals.show');
    Route::get('/companies/{company}/journals/{journal}/edit', [JournalController::class, 'edit'])->name('journals.edit');
    Route::put('/companies/{company}/journals/{journal}', [JournalController::class, 'update'])->name('journals.update');
    Route::delete('/companies/{company}/journals/{journal}', [JournalController::class, 'destroy'])->name('journals.destroy');
    Route::post('/companies/{company}/journals/{journal}/post', [JournalController::class, 'post'])->name('journals.post');
    Route::post('/companies/{company}/journals/{journal}/reverse', [JournalController::class, 'reverse'])->name('journals.reverse');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports');
    Route::get('/reports/general-ledger', [ReportController::class, 'ledger'])->name('reports.ledger');
    Route::get('/reports/trial-balance', [ReportController::class, 'trial'])->name('reports.trial');
    Route::get('/reports/profit-loss', [ReportController::class, 'profitLoss'])->name('reports.profit-loss');
    Route::get('/reports/balance-sheet', [ReportController::class, 'balanceSheet'])->name('reports.balance-sheet');
    Route::get('/sales', [SalesController::class, 'index'])->name('sales');
    Route::get('/companies/{company}/customers', [SalesController::class, 'customers'])->name('sales.customers');
    Route::post('/companies/{company}/customers', [SalesController::class, 'storeCustomer'])->name('sales.customers.store');
    Route::get('/companies/{company}/customers/{customer}/edit', [SalesController::class, 'editCustomer'])->name('sales.customers.edit');
    Route::put('/companies/{company}/customers/{customer}', [SalesController::class, 'updateCustomer'])->name('sales.customers.update');
    Route::patch('/companies/{company}/customers/{customer}/status', [SalesController::class, 'customerStatus'])->name('sales.customers.status');
    Route::get('/companies/{company}/customers/{customer}/delete', [SalesController::class, 'confirmCustomerDelete'])->name('sales.customers.delete');
    Route::delete('/companies/{company}/customers/{customer}', [SalesController::class, 'destroyCustomer'])->name('sales.customers.destroy');
    Route::get('/companies/{company}/items', [SalesController::class, 'items'])->name('sales.items');
    Route::post('/companies/{company}/items', [SalesController::class, 'storeItem'])->name('sales.items.store');
    Route::get('/companies/{company}/items/{item}/edit', [SalesController::class, 'editItem'])->name('sales.items.edit');
    Route::put('/companies/{company}/items/{item}', [SalesController::class, 'updateItem'])->name('sales.items.update');
    Route::patch('/companies/{company}/items/{item}/status', [SalesController::class, 'itemStatus'])->name('sales.items.status');
    Route::get('/companies/{company}/items/{item}/delete', [SalesController::class, 'confirmItemDelete'])->name('sales.items.delete');
    Route::delete('/companies/{company}/items/{item}', [SalesController::class, 'destroyItem'])->name('sales.items.destroy');
    Route::get('/companies/{company}/sales/{type}', [SalesTransactionController::class, 'index'])->name('sales.transactions.index');
    Route::get('/companies/{company}/sales/{type}/create', [SalesTransactionController::class, 'create'])->name('sales.transactions.create');
    Route::post('/companies/{company}/sales/{type}', [SalesTransactionController::class, 'store'])->name('sales.transactions.store');
    Route::get('/companies/{company}/sales/{type}/{document}', [SalesTransactionController::class, 'show'])->whereNumber('document')->name('sales.transactions.show');
    Route::get('/companies/{company}/sales/{type}/{document}/edit', [SalesTransactionController::class, 'edit'])->whereNumber('document')->name('sales.transactions.edit');
    Route::put('/companies/{company}/sales/{type}/{document}', [SalesTransactionController::class, 'update'])->whereNumber('document')->name('sales.transactions.update');
    Route::delete('/companies/{company}/sales/{type}/{document}', [SalesTransactionController::class, 'destroy'])->whereNumber('document')->name('sales.transactions.destroy');
    Route::post('/companies/{company}/sales/{type}/{document}/post', [SalesTransactionController::class, 'post'])->whereNumber('document')->name('sales.transactions.post');
    Route::post('/companies/{company}/quotations/{quotation}/convert', [SalesTransactionController::class, 'convertQuotation'])->name('sales.quotations.convert');
    Route::post('/companies/{company}/orders/{order}/convert', [SalesTransactionController::class, 'convertOrder'])->name('sales.orders.convert');
    Route::get('/companies/{company}/sales-invoices', [SalesTransactionController::class, 'invoicesIndex'])->name('sales.invoices');
    Route::get('/companies/{company}/sales-documents/{type}', [SalesTransactionController::class, 'legacyIndex'])->name('sales.documents');
    Route::post('/companies/{company}/sales-invoices/{invoice}/post', [SalesController::class, 'postInvoice'])->name('sales.invoices.post');
    Route::get('/reports/accounts-receivable', [ReceivablesController::class, 'ar'])->name('reports.ar');
    Route::get('/reports/ar-aging', [ReceivablesController::class, 'aging'])->name('reports.ar-aging');
    Route::get('/reports/customer-statement', [ReceivablesController::class, 'statement'])->name('reports.customer-statement');
    Route::get('/purchases', [PurchasesController::class, 'index'])->name('purchases');
    Route::get('/companies/{company}/suppliers', [PurchasesController::class, 'suppliers'])->name('purchases.suppliers');
    Route::post('/companies/{company}/suppliers', [PurchasesController::class, 'storeSupplier'])->name('purchases.suppliers.store');
    Route::get('/companies/{company}/suppliers/{supplier}/edit', [PurchasesController::class, 'editSupplier'])->name('purchases.suppliers.edit');
    Route::put('/companies/{company}/suppliers/{supplier}', [PurchasesController::class, 'updateSupplier'])->name('purchases.suppliers.update');
    Route::patch('/companies/{company}/suppliers/{supplier}/status', [PurchasesController::class, 'supplierStatus'])->name('purchases.suppliers.status');
    Route::delete('/companies/{company}/suppliers/{supplier}', [PurchasesController::class, 'deleteSupplier'])->name('purchases.suppliers.destroy');
    Route::get('/companies/{company}/purchases/{type}', [PurchasesController::class, 'documents'])->name('purchases.documents');
    Route::get('/companies/{company}/purchases/{type}/create', [PurchasesController::class, 'createDocument'])->name('purchases.documents.create');
    Route::post('/companies/{company}/purchases/{type}', [PurchasesController::class, 'storeDocument'])->name('purchases.documents.store');
    Route::get('/companies/{company}/purchases/{type}/{document}', [PurchasesController::class, 'showDocument'])->whereNumber('document')->name('purchases.documents.show');
    Route::get('/companies/{company}/purchases/{type}/{document}/edit', [PurchasesController::class, 'editDocument'])->whereNumber('document')->name('purchases.documents.edit');
    Route::put('/companies/{company}/purchases/{type}/{document}', [PurchasesController::class, 'updateDocument'])->whereNumber('document')->name('purchases.documents.update');
    Route::delete('/companies/{company}/purchases/{type}/{document}', [PurchasesController::class, 'destroyDocument'])->whereNumber('document')->name('purchases.documents.destroy');
    Route::post('/companies/{company}/purchases/{type}/{document}/post', [PurchasesController::class, 'postDocument'])->whereNumber('document')->name('purchases.documents.post');
    Route::post('/companies/{company}/purchase-orders/{order}/convert', [PurchasesController::class, 'convertOrder'])->name('purchases.orders.convert');
    Route::get('/reports/accounts-payable/{type}', [PurchasesController::class, 'report'])->name('purchases.reports');
    Route::get('/banking', [BankingController::class, 'index'])->name('banking');
    Route::get('/period-end', [PeriodEndController::class, 'index'])->name('period-end');
    Route::get('/period-end/{country}', [PeriodEndController::class, 'country'])->name('period-end.country');
    Route::get('/period-end/{country}/entities/{company}', [PeriodEndController::class, 'entity'])->name('period-end.entity');
    Route::patch('/period-end/{country}/entities/{company}/locks', [PeriodEndController::class, 'locks'])->name('period-end.locks');
    Route::get('/period-end/{country}/entities/{company}/years/{year}', [PeriodEndController::class, 'year'])->name('period-end.year');
    Route::post('/period-end/{country}/entities/{company}/years/{year}/close', [PeriodEndController::class, 'closeYear'])->name('period-end.year.close');
    Route::get('/period-end/{country}/entities/{company}/years/{year}/periods/{period}', [PeriodEndController::class, 'workspace'])->name('period-end.workspace');
    Route::post('/period-end/{country}/entities/{company}/years/{year}/periods/{period}/adjustments', [PeriodEndController::class, 'adjustment'])->name('period-end.adjustments.store');
    Route::patch('/period-end/{country}/entities/{company}/years/{year}/periods/{period}/checklist/{item}', [PeriodEndController::class, 'checklist'])->name('period-end.checklist.update');
    Route::post('/period-end/{country}/entities/{company}/years/{year}/periods/{period}/close', [PeriodEndController::class, 'closePeriod'])->name('period-end.period.close');
    Route::post('/period-end/{country}/entities/{company}/years/{year}/periods/{period}/reopen', [PeriodEndController::class, 'reopenPeriod'])->name('period-end.period.reopen');
    Route::post('/period-end/{country}/entities/{company}/reversals/{schedule}/post', [PeriodEndController::class, 'postReversal'])->name('period-end.reversals.post');
    Route::get('/banking/{country}', [BankingController::class, 'country'])->name('banking.country');
    Route::get('/banking/{country}/entities/{company}/accounts', [BankingController::class, 'accounts'])->name('banking.accounts');
    Route::post('/banking/{country}/entities/{company}/accounts', [BankingController::class, 'storeAccount'])->name('banking.accounts.store');
    Route::put('/banking/{country}/entities/{company}/accounts/{account}', [BankingController::class, 'updateAccount'])->name('banking.accounts.update');
    Route::patch('/banking/{country}/entities/{company}/accounts/{account}/status', [BankingController::class, 'status'])->name('banking.accounts.status');
    Route::delete('/banking/{country}/entities/{company}/accounts/{account}', [BankingController::class, 'destroy'])->name('banking.accounts.destroy');
    Route::get('/banking/{country}/entities/{company}/accounts/{account}/register', [BankingController::class, 'register'])->name('banking.register');
    Route::get('/banking/{country}/entities/{company}/transactions/create', [BankingController::class, 'createTransaction'])->name('banking.transactions.create');
    Route::post('/banking/{country}/entities/{company}/transactions', [BankingController::class, 'storeTransaction'])->name('banking.transactions.store');
    Route::get('/banking/{country}/entities/{company}/accounts/{account}/imports', [BankingController::class, 'imports'])->name('banking.imports');
    Route::post('/banking/{country}/entities/{company}/accounts/{account}/imports/preview', [BankingController::class, 'preview'])->name('banking.imports.preview');
    Route::post('/banking/{country}/entities/{company}/accounts/{account}/imports', [BankingController::class, 'confirmImport'])->name('banking.imports.confirm');
    Route::get('/banking/{country}/entities/{company}/accounts/{account}/matching', [BankingController::class, 'matching'])->name('banking.matching');
    Route::post('/banking/{country}/entities/{company}/accounts/{account}/matching/{row}', [BankingController::class, 'match'])->name('banking.match');
    Route::post('/banking/{country}/entities/{company}/accounts/{account}/matching/{row}/create', [BankingController::class, 'createFromStatement'])->name('banking.match.create');
    Route::get('/banking/{country}/entities/{company}/accounts/{account}/reconciliations', [BankingController::class, 'reconciliations'])->name('banking.reconciliations');
    Route::post('/banking/{country}/entities/{company}/accounts/{account}/reconciliations', [BankingController::class, 'storeReconciliation'])->name('banking.reconciliations.store');
    Route::post('/banking/{country}/entities/{company}/accounts/{account}/reconciliations/{reconciliation}/complete', [BankingController::class, 'completeReconciliation'])->name('banking.reconciliations.complete');
    Route::get('/tax', [TaxController::class, 'index'])->name('tax');
    Route::get('/tax/{country}', [TaxController::class, 'country'])->name('tax.country');
    Route::get('/tax/{country}/entities/{company}', [TaxController::class, 'workspace'])->name('tax.workspace');
    Route::get('/tax/{country}/entities/{company}/register', [TaxController::class, 'workspace'])->name('tax.register');
    Route::get('/tax/{country}/entities/{company}/output-tax', [TaxController::class, 'workspace'])->name('tax.output');
    Route::get('/tax/{country}/entities/{company}/input-tax', [TaxController::class, 'workspace'])->name('tax.input');
    Route::get('/tax/{country}/entities/{company}/summary', [TaxController::class, 'workspace'])->name('tax.summary');
    Route::get('/tax/{country}/entities/{company}/adjustments', [TaxController::class, 'workspace'])->name('tax.adjustments');
    Route::post('/tax/{country}/entities/{company}/registrations', [TaxController::class, 'storeRegistration'])->name('tax.registrations.store');
    Route::get('/tax/{country}/entities/{company}/registrations/{registration}/edit', [TaxController::class, 'editRegistration'])->name('tax.registrations.edit');
    Route::put('/tax/{country}/entities/{company}/registrations/{registration}', [TaxController::class, 'updateRegistration'])->name('tax.registrations.update');
    Route::post('/tax/{country}/entities/{company}/codes', [TaxController::class, 'storeCode'])->name('tax.codes.store');
    Route::get('/tax/{country}/entities/{company}/codes/{code}/edit', [TaxController::class, 'editCode'])->name('tax.codes.edit');
    Route::put('/tax/{country}/entities/{company}/codes/{code}', [TaxController::class, 'updateCode'])->name('tax.codes.update');
    Route::post('/tax/{country}/entities/{company}/codes/{code}/rates', [TaxController::class, 'storeRate'])->name('tax.rates.store');
    Route::get('/tax/{country}/entities/{company}/codes/{code}/rates/{rate}/edit', [TaxController::class, 'editRate'])->name('tax.rates.edit');
    Route::put('/tax/{country}/entities/{company}/codes/{code}/rates/{rate}', [TaxController::class, 'updateRate'])->name('tax.rates.update');
    Route::put('/tax/{country}/entities/{company}/settings', [TaxController::class, 'settings'])->name('tax.settings.update');
    Route::post('/tax/{country}/entities/{company}/registrations/{registration}/periods', [TaxController::class, 'generatePeriods'])->name('tax.periods.generate');
    Route::post('/tax/{country}/entities/{company}/periods/{period}/prepare', [TaxController::class, 'preparePeriod'])->name('tax.periods.prepare');
    Route::post('/tax/{country}/entities/{company}/periods/{period}/file', [TaxController::class, 'filePeriod'])->name('tax.periods.file');
    Route::post('/tax/{country}/entities/{company}/adjustments', [TaxController::class, 'adjustment'])->name('tax.adjustments.store');
    foreach (['settings'] as $module) {
        Route::view("/{$module}", 'coming-soon.index', ['module' => ucfirst($module)])->name($module);
    }
});
