@extends('layouts.app')
@section('content')
<h1>Edit Company</h1>
<div class="card p-4"><form method="post" action="{{ route('companies.update', $company) }}" class="row g-3">@csrf @method('PUT')
@foreach(['name' => 'Company Name', 'legal_name' => 'Legal / Business Name', 'email' => 'Email', 'phone' => 'Phone', 'timezone' => 'Timezone'] as $field => $label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ $field }}" value="{{ old($field, $company->{$field}) }}" @required(in_array($field, ['name', 'legal_name', 'timezone']))></div>@endforeach
<div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address">{{ old('address', $company->address) }}</textarea></div>
<div class="col-md-6"><label class="form-label">Country / Tax Jurisdiction</label><select class="form-select" id="country-id" name="country_id" @disabled($countryLocked)>@foreach($countries as $country)<option value="{{ $country->id }}" @selected($company->country_id === $country->id)>{{ $country->name }}</option>@endforeach</select>@if($countryLocked)<input type="hidden" name="country_id" value="{{ $company->country_id }}">@endif</div>
<div class="col-md-6"><label class="form-label">Base Currency</label><select class="form-select" name="base_currency_id" @disabled($countryLocked)>@foreach($currencies as $currency)<option data-code="{{ $currency->code }}" value="{{ $currency->id }}" @selected($company->base_currency_id === $currency->id)>{{ $currency->code }} — {{ $currency->name }}</option>@endforeach</select>@if($countryLocked)<input type="hidden" name="base_currency_id" value="{{ $company->base_currency_id }}">@endif</div>
@if($countryLocked)<div class="col-12 alert alert-warning">Country / Tax Jurisdiction and Base Currency cannot be changed after accounting or business activity exists.</div>@else<div class="col-12 alert alert-info">This entity has no business or accounting activity. Changing jurisdiction will update the suggested timezone and base currency; review both before saving.</div>@endif
<div class="d-flex gap-2"><a class="btn btn-secondary" href="{{ route('companies.show', $company) }}">Cancel</a><button class="btn btn-primary">Save Changes</button></div>
</form></div>
@unless($countryLocked)<script>const country=document.querySelector('#country-id'),defaults=@json($jurisdictionDefaults);country.addEventListener('change',()=>{const suggested=defaults[country.value];if(!suggested)return;document.querySelector('[name="timezone"]').value=suggested.timezone;const currency=document.querySelector('[name="base_currency_id"] option[data-code="'+suggested.currency+'"]');if(currency)currency.selected=true})</script>@endunless
@endsection
