@extends('layouts.app')
@section('content')
@php
    $editing = (bool) $document;
    $dateField = ['quotations'=>'quotation_date','orders'=>'order_date','invoices'=>'invoice_date','credit-notes'=>'credit_note_date','receipts'=>'receipt_date'][$type];
    $lines = old('lines', $editing && method_exists($document,'lines') ? $document->lines->map(fn($line)=>['item_id'=>$line->item_id ?? null,'revenue_account_id'=>$line->revenue_account_id,'description'=>$line->description,'quantity'=>number_format((float)$line->quantity,2,'.',''),'unit_price'=>number_format((float)$line->unit_price,2,'.',''),'discount'=>number_format((float)($line->discount ?? 0),2,'.',''),'tax_code_id'=>$line->tax_code_id ?? null,'tax_inclusive'=>$line->tax_inclusive ?? false])->all() : [['item_id'=>'','revenue_account_id'=>'','description'=>'','quantity'=>'1.00','unit_price'=>'0.00','discount'=>'0.00','tax_code_id'=>null,'tax_inclusive'=>false]]);
    $attemptedDate = old($dateField);
    $blockedYear = $attemptedDate ? $years->first(fn($year) => $attemptedDate >= $year->starts_on->toDateString() && $attemptedDate <= $year->ends_on->toDateString() && in_array($year->status, ['closed','filed'])) : null;
    $salesYearContext = $years->map(fn($year) => [
        'id' => $year->id,
        'name' => $year->name,
        'status' => $year->status,
        'starts_on' => $year->starts_on->toDateString(),
        'ends_on' => $year->ends_on->toDateString(),
        'periods' => $year->periods->map(fn($period) => [
            'id' => $period->id,
            'name' => $period->name,
            'status' => $period->status,
            'starts_on' => $period->starts_on->toDateString(),
            'ends_on' => $period->ends_on->toDateString(),
        ])->values(),
    ])->values();
@endphp
<h1>{{ $editing ? 'Edit Draft' : 'New '.$singular }}</h1><p class="text-muted">{{ $company->name }} · {{ $company->baseCurrency->code }}</p>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($blockedYear)<div class="mb-3"><a class="btn btn-outline-primary" href="{{ route('companies.prior-adjustments.create', [$company, 'origin_financial_year_id' => $blockedYear->id]) }}">Create Prior-Period Adjustment</a></div>@endif
<form method="post" action="{{ $editing ? route('sales.transactions.update',[$company,$type,$document]) : route('sales.transactions.store',[$company,$type]) }}" class="card p-4">@csrf @if($editing) @method('PUT') @endif
<div class="row g-3"><div class="col-md-4"><label class="form-label">Customer</label><select name="customer_id" class="form-select" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id',$document?->customer_id)==$customer->id)>{{ $customer->code }} — {{ $customer->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Branch</label><select name="branch_id" class="form-select" required><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id',$document?->branch_id ?? ($branches->count()===1?$branch->id:null))==$branch->id)>{{ $branch->code }} — {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">{{ ucwords(str_replace('_',' ',$dateField)) }}</label><input type="date" name="{{ $dateField }}" class="form-control" value="{{ old($dateField, data_get($document, $dateField)?->toDateString() ?? today()->toDateString()) }}" required></div>
@if($type==='quotations')<div class="col-md-4"><label class="form-label">Valid Until</label><input type="date" name="expiry_date" class="form-control" value="{{ old('expiry_date',$document?->expiry_date?->toDateString()) }}"></div>@endif
<div class="col-md-4"><label class="form-label">Financial Year</label><select name="financial_year_id" class="form-select"><option value="">Resolve from transaction date</option>@foreach($years as $year)<option value="{{ $year->id }}" @selected(old('financial_year_id',$document?->financial_year_id)==$year->id)>{{ $year->name }} ({{ ucfirst($year->status) }})</option>@endforeach</select></div>
@if(in_array($type,['invoices','credit-notes','receipts']))<div class="col-md-4"><label class="form-label">Accounting Period</label><select name="accounting_period_id" class="form-select"><option value="">Resolve from transaction date</option>@foreach($years as $year) @foreach($year->periods as $period)<option value="{{ $period->id }}" @selected(old('accounting_period_id',$document?->accounting_period_id)==$period->id)>{{ $year->name }} · {{ $period->name }} ({{ ucfirst($period->status) }})</option>@endforeach @endforeach</select></div>@endif
@if($type==='invoices')<div class="col-md-4"><label class="form-label">Due Date</label><input type="date" name="due_date" class="form-control" value="{{ old('due_date',$document?->due_date?->toDateString()) }}" required></div>@endif
@if($type==='credit-notes')<div class="col-md-8"><label class="form-label">Original Posted Invoice</label><select name="sales_invoice_id" class="form-select" required><option value="">Select invoice</option>@foreach($invoices as $invoice)<option value="{{ $invoice->id }}" @selected(old('sales_invoice_id',$document?->sales_invoice_id)==$invoice->id)>{{ $invoice->invoice_number }} — {{ $invoice->customer->name }} — Outstanding {{ number_format((float)$invoice->amount_due,2) }}</option>@endforeach</select></div>@endif
@if(in_array($type,['quotations','orders','invoices']))<div class="col-md-4"><label class="form-label">Customer Reference</label><input name="customer_reference" class="form-control" value="{{ old('customer_reference',$document?->customer_reference) }}"></div><div class="col-12"><label class="form-label">Notes</label><textarea name="notes" class="form-control">{{ old('notes',$document?->notes) }}</textarea></div>@endif
@if($type==='credit-notes')<div class="col-12"><label class="form-label">Reason / Notes</label><textarea name="notes" class="form-control">{{ old('notes',$document?->notes) }}</textarea></div>@endif
@if($type==='receipts')<div class="col-md-4"><label class="form-label">Receipt Amount ({{ $company->baseCurrency->code }})</label><input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" class="form-control sales-decimal-input" value="{{ old('amount',$document?->amount) }}" required></div><div class="col-md-4"><label class="form-label">Payment Method</label><select name="payment_method" class="form-select"><option>Bank Transfer</option><option>Cash</option><option>Card</option><option>Cheque</option></select></div><div class="col-md-4"><label class="form-label">Payment Reference</label><input name="reference" class="form-control" value="{{ old('reference',$document?->reference) }}"></div><div class="col-md-6"><label class="form-label">Receiving Cash / Bank Account</label><select name="receiving_account_id" class="form-select" required>@foreach($accounts->where('type','asset') as $account)<option value="{{ $account->id }}" @selected(old('receiving_account_id',$document?->receiving_account_id)==$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div>@endif</div>
<div id="sales-period-context" class="alert alert-info mt-3 mb-0">Financial Year and Accounting Period will be resolved from the transaction date.</div>
<script>const salesYears=@json($salesYearContext);function resolveSalesPeriod(){const date=document.querySelector('[name="{{ $dateField }}"]')?.value,box=document.querySelector('#sales-period-context');if(!date)return;const matches=salesYears.filter(year=>date>=year.starts_on&&date<=year.ends_on);if(matches.length!==1){box.className='alert alert-danger mt-3 mb-0';box.textContent='No unique Financial Year exists for '+date+'.';return}const year=matches[0],period=year.periods.find(item=>date>=item.starts_on&&date<=item.ends_on);box.className='alert '+(year.status==='open'&&period?.status==='open'?'alert-info':'alert-warning')+' mt-3 mb-0';box.textContent='Resolved context: Financial Year '+year.name+' ('+year.status+') · Accounting Period '+(period?period.name+' ('+period.status+')':'not configured')}document.querySelector('[name="{{ $dateField }}"]')?.addEventListener('change',event=>{document.querySelector('[name="financial_year_id"]').value='';const period=document.querySelector('[name="accounting_period_id"]');if(period)period.value='';resolveSalesPeriod()});resolveSalesPeriod()</script>
@if($type==='receipts')
<h5 class="mt-4">Invoice Allocation</h5><div class="table-responsive"><table class="table"><thead><tr><th>Invoice</th><th>Total</th><th>Previously Paid</th><th>Outstanding</th><th>Allocate</th></tr></thead><tbody>@foreach($invoices as $index=>$invoice)<tr><td>{{ $invoice->invoice_number }} — {{ $invoice->customer->name }}<input type="hidden" name="allocations[{{ $index }}][sales_invoice_id]" value="{{ $invoice->id }}"></td><td>{{ number_format((float)$invoice->total,2) }}</td><td>{{ number_format((float)$invoice->amount_paid,2) }}</td><td>{{ number_format((float)$invoice->amount_due,2) }}</td><td><input type="number" min="0" max="{{ $invoice->amount_due }}" step="0.01" inputmode="decimal" name="allocations[{{ $index }}][amount]" class="form-control sales-decimal-input" value="{{ old("allocations.$index.amount",$document?->allocations?->firstWhere('sales_invoice_id',$invoice->id)?->amount ?? '0.00') }}"></td></tr>@endforeach</tbody></table></div>
@else
<div class="d-flex justify-content-between align-items-center mt-4 mb-2"><h5 class="mb-0">Line Items</h5><button type="button" class="btn btn-outline-primary" onclick="addSalesLine()">+ Add Line</button></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Product / Service</th><th>Description</th><th>Quantity</th><th>Unit Price ({{ $company->baseCurrency->code }})</th>@if($type!=='credit-notes')<th>Discount Amount ({{ $company->baseCurrency->code }})</th>@endif @if(in_array($type,['invoices','credit-notes']))<th>Tax Code</th>@endif<th>Action</th></tr></thead><tbody id="sales-lines">@foreach($lines as $index=>$line)<tr><td><select name="lines[{{ $index }}][item_id]" class="form-select item-select" onchange="fillItem(this)"><option value="">Custom line</option>@foreach($items as $item)<option value="{{ $item->id }}" data-description="{{ $item->description ?: $item->name }}" data-price="{{ number_format((float)$item->sales_price,2,'.','') }}" data-account="{{ $item->revenue_account_id }}" @selected(($line['item_id']??null)==$item->id)>{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><input type="hidden" class="revenue-account" name="lines[{{ $index }}][revenue_account_id]" value="{{ $line['revenue_account_id']??'' }}"></td><td><input class="form-control description" name="lines[{{ $index }}][description]" value="{{ $line['description']??'' }}" required></td><td><input class="form-control sales-decimal-input quantity" name="lines[{{ $index }}][quantity]" type="number" min="0.01" step="0.01" inputmode="decimal" value="{{ $line['quantity']??'1.00' }}" required></td><td><input class="form-control sales-decimal-input price" name="lines[{{ $index }}][unit_price]" type="number" min="0" step="0.01" inputmode="decimal" value="{{ $line['unit_price']??'0.00' }}" required></td>@if($type!=='credit-notes')<td><input class="form-control sales-decimal-input discount" name="lines[{{ $index }}][discount]" type="number" min="0" step="0.01" inputmode="decimal" value="{{ $line['discount']??'0.00' }}" aria-label="Discount amount"></td>@endif @if(in_array($type,['invoices','credit-notes']))<td><select class="form-select tax-code" name="lines[{{$index}}][tax_code_id]"><option value="">No tax snapshot</option>@foreach($taxCodes as $taxCode)<option value="{{$taxCode->id}}" @selected(($line['tax_code_id']??null)==$taxCode->id)>{{$taxCode->code}} — {{str($taxCode->treatment)->replace('_',' ')->title()}}</option>@endforeach</select><label class="small"><input type="checkbox" name="lines[{{$index}}][tax_inclusive]" value="1" @checked($line['tax_inclusive']??false)> Price includes tax</label></td>@endif<td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeSalesLine(this)">Remove</button></td></tr>@endforeach</tbody></table></div>
@endif
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary">{{ $editing?'Update Draft':'Save Draft' }}</button><a class="btn btn-outline-secondary" href="{{ route('sales.transactions.index',[$company,$type]) }}">Cancel</a></div></form>
@if($type!=='receipts')<template id="sales-line-template"><tr><td><select class="form-select item-select" onchange="fillItem(this)"><option value="">Custom line</option>@foreach($items as $item)<option value="{{ $item->id }}" data-description="{{ $item->description ?: $item->name }}" data-price="{{ number_format((float)$item->sales_price,2,'.','') }}" data-account="{{ $item->revenue_account_id }}">{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><input type="hidden" class="revenue-account"></td><td><input class="form-control description" required></td><td><input class="form-control quantity" type="number" min="0.01" step="0.01" value="1.00" required></td><td><input class="form-control price" type="number" min="0" step="0.01" value="0.00" required></td>@if($type!=='credit-notes')<td><input class="form-control discount" type="number" min="0" step="0.01" value="0.00" aria-label="Discount amount"></td>@endif @if(in_array($type,['invoices','credit-notes']))<td><select class="form-select tax-code"><option value="">No tax snapshot</option>@foreach($taxCodes as $taxCode)<option value="{{$taxCode->id}}">{{$taxCode->code}} — {{str($taxCode->treatment)->replace('_',' ')->title()}}</option>@endforeach</select><label class="small"><input type="checkbox" class="tax-inclusive" value="1"> Price includes tax</label></td>@endif<td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeSalesLine(this)">Remove</button></td></tr></template><script>let nextLine={{count($lines)}};function fillItem(select){let option=select.selectedOptions[0],row=select.closest('tr');if(option.value){row.querySelector('.description').value=option.dataset.description;row.querySelector('.price').value=option.dataset.price;row.querySelector('.revenue-account').value=option.dataset.account}calculateSalesTotals()}function addSalesLine(){let fragment=document.querySelector('#sales-line-template').content.cloneNode(true),row=fragment.querySelector('tr');row.querySelector('.item-select').name=`lines[${nextLine}][item_id]`;row.querySelector('.revenue-account').name=`lines[${nextLine}][revenue_account_id]`;row.querySelector('.description').name=`lines[${nextLine}][description]`;row.querySelector('.quantity').name=`lines[${nextLine}][quantity]`;row.querySelector('.price').name=`lines[${nextLine}][unit_price]`;let discount=row.querySelector('.discount');if(discount)discount.name=`lines[${nextLine}][discount]`;let taxCode=row.querySelector('.tax-code'),taxInclusive=row.querySelector('.tax-inclusive');if(taxCode)taxCode.name=`lines[${nextLine}][tax_code_id]`;if(taxInclusive)taxInclusive.name=`lines[${nextLine}][tax_inclusive]`;document.querySelector('#sales-lines').append(fragment);nextLine++}function removeSalesLine(button){button.closest('tr').remove();calculateSalesTotals()}</script>@endif
@if($type!=='receipts')<script>const salesBody=document.querySelector('#sales-lines'),salesTable=salesBody.closest('table'),amountHeading=document.createElement('th');amountHeading.textContent='Line Amount';salesTable.querySelector('thead tr').insertBefore(amountHeading,salesTable.querySelector('thead tr').lastElementChild);const totalBox=document.createElement('div');totalBox.className='text-end fs-5 fw-bold mb-3';salesTable.parentElement.after(totalBox);function scaledDecimal(value){let text=String(value||'0').trim(),negative=text.startsWith('-');if(negative)text=text.slice(1);let [whole='0',fraction='']=text.split('.');fraction=(fraction+'0000').slice(0,4);let scaled=BigInt(whole||'0')*10000n+BigInt(fraction||'0');return negative?-scaled:scaled}function displayMoney(value){let negative=value<0n;if(negative)value=-value;let cents=(value+50n)/100n,whole=cents/100n,fraction=String(cents%100n).padStart(2,'0');return (negative?'-':'')+whole+'.'+fraction}function calculateSalesTotals(){let total=0n;salesBody.querySelectorAll('tr').forEach(row=>{if(!row.querySelector('.line-amount')){let cell=document.createElement('td');cell.className='line-amount text-end';row.insertBefore(cell,row.lastElementChild)}let quantity=scaledDecimal(row.querySelector('.quantity')?.value),price=scaledDecimal(row.querySelector('.price')?.value),discount=scaledDecimal(row.querySelector('.discount')?.value),amount=(quantity*price)/10000n-discount;row.querySelector('.line-amount').textContent='{{ $company->baseCurrency->code }} '+displayMoney(amount);total+=amount});totalBox.textContent='Document Total: {{ $company->baseCurrency->code }} '+displayMoney(total)}salesBody.addEventListener('input',calculateSalesTotals);salesBody.addEventListener('change',calculateSalesTotals);new MutationObserver(calculateSalesTotals).observe(salesBody,{childList:true});calculateSalesTotals()</script>@endif
@endsection
