@extends('layouts.app')
@section('content')
@php
    $editing = (bool) $document;
    $dateField = ['quotations'=>'quotation_date','orders'=>'order_date','invoices'=>'invoice_date','credit-notes'=>'credit_note_date','receipts'=>'receipt_date'][$type];
    $lines = old('lines', $editing && method_exists($document,'lines') ? $document->lines->map(fn($line)=>['item_id'=>$line->item_id ?? null,'revenue_account_id'=>$line->revenue_account_id,'description'=>$line->description,'quantity'=>$line->quantity,'unit_price'=>$line->unit_price,'discount'=>$line->discount ?? 0])->all() : [['item_id'=>'','revenue_account_id'=>'','description'=>'','quantity'=>'1.00','unit_price'=>'0.00','discount'=>'0.00']]);
@endphp
<h1>{{ $editing ? 'Edit Draft' : 'New '.$singular }}</h1><p class="text-muted">{{ $company->name }} · {{ $company->baseCurrency->code }}</p>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ $editing ? route('sales.transactions.update',[$company,$type,$document]) : route('sales.transactions.store',[$company,$type]) }}" class="card p-4">@csrf @if($editing) @method('PUT') @endif
<div class="row g-3"><div class="col-md-4"><label class="form-label">Customer</label><select name="customer_id" class="form-select" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id',$document?->customer_id)==$customer->id)>{{ $customer->code }} — {{ $customer->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Branch</label><select name="branch_id" class="form-select" required><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id',$document?->branch_id ?? ($branches->count()===1?$branch->id:null))==$branch->id)>{{ $branch->code }} — {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">{{ ucwords(str_replace('_',' ',$dateField)) }}</label><input type="date" name="{{ $dateField }}" class="form-control" value="{{ old($dateField,$document?->{$dateField}?->toDateString() ?? today()->toDateString()) }}" required></div>
@if($type==='quotations')<div class="col-md-4"><label class="form-label">Valid Until</label><input type="date" name="expiry_date" class="form-control" value="{{ old('expiry_date',$document?->expiry_date?->toDateString()) }}"></div>@endif
@if(in_array($type,['invoices','credit-notes','receipts']))<div class="col-md-4"><label class="form-label">Accounting Period</label><select name="accounting_period_id" class="form-select" required>@foreach($years as $year) @foreach($year->periods as $period)<option value="{{ $period->id }}" @selected(old('accounting_period_id',$document?->accounting_period_id)==$period->id)>{{ $period->name }}</option>@endforeach @endforeach</select></div>@endif
@if($type==='invoices')<div class="col-md-4"><label class="form-label">Due Date</label><input type="date" name="due_date" class="form-control" value="{{ old('due_date',$document?->due_date?->toDateString()) }}" required></div>@endif
@if($type==='credit-notes')<div class="col-md-8"><label class="form-label">Original Posted Invoice</label><select name="sales_invoice_id" class="form-select" required><option value="">Select invoice</option>@foreach($invoices as $invoice)<option value="{{ $invoice->id }}" @selected(old('sales_invoice_id',$document?->sales_invoice_id)==$invoice->id)>{{ $invoice->invoice_number }} — {{ $invoice->customer->name }} — Outstanding {{ number_format((float)$invoice->amount_due,2) }}</option>@endforeach</select></div>@endif
@if(in_array($type,['quotations','orders','invoices']))<div class="col-md-4"><label class="form-label">Customer Reference</label><input name="customer_reference" class="form-control" value="{{ old('customer_reference',$document?->customer_reference) }}"></div><div class="col-12"><label class="form-label">Notes</label><textarea name="notes" class="form-control">{{ old('notes',$document?->notes) }}</textarea></div>@endif
@if($type==='credit-notes')<div class="col-12"><label class="form-label">Reason / Notes</label><textarea name="notes" class="form-control">{{ old('notes',$document?->notes) }}</textarea></div>@endif
@if($type==='receipts')<div class="col-md-4"><label class="form-label">Receipt Amount ({{ $company->baseCurrency->code }})</label><input name="amount" type="number" min="0.01" step="0.01" class="form-control" value="{{ old('amount',$document?->amount) }}" required></div><div class="col-md-4"><label class="form-label">Payment Method</label><select name="payment_method" class="form-select"><option>Bank Transfer</option><option>Cash</option><option>Card</option><option>Cheque</option></select></div><div class="col-md-4"><label class="form-label">Payment Reference</label><input name="reference" class="form-control" value="{{ old('reference',$document?->reference) }}"></div><div class="col-md-6"><label class="form-label">Receiving Cash / Bank Account</label><select name="receiving_account_id" class="form-select" required>@foreach($accounts->where('type','asset') as $account)<option value="{{ $account->id }}" @selected(old('receiving_account_id',$document?->receiving_account_id)==$account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div>@endif</div>
@if($type==='receipts')
<h5 class="mt-4">Invoice Allocation</h5><div class="table-responsive"><table class="table"><thead><tr><th>Invoice</th><th>Total</th><th>Previously Paid</th><th>Outstanding</th><th>Allocate</th></tr></thead><tbody>@foreach($invoices as $index=>$invoice)<tr><td>{{ $invoice->invoice_number }} — {{ $invoice->customer->name }}<input type="hidden" name="allocations[{{ $index }}][sales_invoice_id]" value="{{ $invoice->id }}"></td><td>{{ number_format((float)$invoice->total,2) }}</td><td>{{ number_format((float)$invoice->amount_paid,2) }}</td><td>{{ number_format((float)$invoice->amount_due,2) }}</td><td><input type="number" min="0" max="{{ $invoice->amount_due }}" step="0.01" name="allocations[{{ $index }}][amount]" class="form-control" value="{{ old("allocations.$index.amount",$document?->allocations?->firstWhere('sales_invoice_id',$invoice->id)?->amount ?? '0.00') }}"></td></tr>@endforeach</tbody></table></div>
@else
<h5 class="mt-4">Line Items</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Product / Service</th><th>Description</th><th>Quantity</th><th>Unit Price</th>@if($type!=='credit-notes')<th>Discount</th>@endif<th>Action</th></tr></thead><tbody id="sales-lines">@foreach($lines as $index=>$line)<tr><td><select name="lines[{{ $index }}][item_id]" class="form-select item-select" onchange="fillItem(this)"><option value="">Custom line</option>@foreach($items as $item)<option value="{{ $item->id }}" data-description="{{ $item->description ?: $item->name }}" data-price="{{ $item->sales_price }}" data-account="{{ $item->revenue_account_id }}" @selected(($line['item_id']??null)==$item->id)>{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><input type="hidden" class="revenue-account" name="lines[{{ $index }}][revenue_account_id]" value="{{ $line['revenue_account_id']??'' }}"></td><td><input class="form-control description" name="lines[{{ $index }}][description]" value="{{ $line['description']??'' }}" required></td><td><input class="form-control quantity" name="lines[{{ $index }}][quantity]" type="number" min="0.0001" step="0.0001" value="{{ $line['quantity']??1 }}" required></td><td><input class="form-control price" name="lines[{{ $index }}][unit_price]" type="number" min="0" step="0.01" value="{{ $line['unit_price']??0 }}" required></td>@if($type!=='credit-notes')<td><input class="form-control discount" name="lines[{{ $index }}][discount]" type="number" min="0" step="0.01" value="{{ $line['discount']??0 }}"></td>@endif<td><button type="button" class="btn btn-sm btn-outline-danger" onclick="this.closest('tr').remove()">Remove</button></td></tr>@endforeach</tbody></table></div><button type="button" class="btn btn-outline-secondary" onclick="addSalesLine()">Add Line</button>
@endif
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary">{{ $editing?'Update Draft':'Save Draft' }}</button><a class="btn btn-outline-secondary" href="{{ route('sales.transactions.index',[$company,$type]) }}">Cancel</a></div></form>
@if($type!=='receipts')<template id="sales-line-template"><tr><td><select class="form-select item-select" onchange="fillItem(this)"><option value="">Custom line</option>@foreach($items as $item)<option value="{{ $item->id }}" data-description="{{ $item->description ?: $item->name }}" data-price="{{ $item->sales_price }}" data-account="{{ $item->revenue_account_id }}">{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><input type="hidden" class="revenue-account"></td><td><input class="form-control description" required></td><td><input class="form-control quantity" type="number" min="0.0001" step="0.0001" value="1.00" required></td><td><input class="form-control price" type="number" min="0" step="0.01" value="0.00" required></td>@if($type!=='credit-notes')<td><input class="form-control discount" type="number" min="0" step="0.01" value="0.00"></td>@endif<td><button type="button" class="btn btn-sm btn-outline-danger" onclick="this.closest('tr').remove()">Remove</button></td></tr></template><script>let nextLine={{count($lines)}};function fillItem(select){let option=select.selectedOptions[0],row=select.closest('tr');if(option.value){row.querySelector('.description').value=option.dataset.description;row.querySelector('.price').value=Number(option.dataset.price).toFixed(2);row.querySelector('.revenue-account').value=option.dataset.account}}function addSalesLine(){let fragment=document.querySelector('#sales-line-template').content.cloneNode(true),row=fragment.querySelector('tr');row.querySelector('.item-select').name=`lines[${nextLine}][item_id]`;row.querySelector('.revenue-account').name=`lines[${nextLine}][revenue_account_id]`;row.querySelector('.description').name=`lines[${nextLine}][description]`;row.querySelector('.quantity').name=`lines[${nextLine}][quantity]`;row.querySelector('.price').name=`lines[${nextLine}][unit_price]`;let discount=row.querySelector('.discount');if(discount)discount.name=`lines[${nextLine}][discount]`;document.querySelector('#sales-lines').append(fragment);nextLine++}</script>@endif
@if($type!=='receipts')<script>const salesBody=document.querySelector('#sales-lines'),salesTable=salesBody.closest('table'),amountHeading=document.createElement('th');amountHeading.textContent='Line Amount';salesTable.querySelector('thead tr').insertBefore(amountHeading,salesTable.querySelector('thead tr').lastElementChild);const totalBox=document.createElement('div');totalBox.className='text-end fs-5 fw-bold mb-3';salesTable.parentElement.after(totalBox);function calculateSalesTotals(){let total=0;salesBody.querySelectorAll('tr').forEach(row=>{if(!row.querySelector('.line-amount')){let cell=document.createElement('td');cell.className='line-amount text-end';row.insertBefore(cell,row.lastElementChild)}let quantity=Number(row.querySelector('.quantity')?.value||0),price=Number(row.querySelector('.price')?.value||0),discount=Number(row.querySelector('.discount')?.value||0),amount=quantity*price-discount;row.querySelector('.line-amount').textContent='{{ $company->baseCurrency->code }} '+amount.toFixed(2);total+=amount});totalBox.textContent='Total: {{ $company->baseCurrency->code }} '+total.toFixed(2)}salesBody.addEventListener('input',calculateSalesTotals);salesBody.addEventListener('change',()=>setTimeout(calculateSalesTotals));new MutationObserver(calculateSalesTotals).observe(salesBody,{childList:true});calculateSalesTotals()</script>@endif
@endsection
