@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="mb-0">{{ $document->{$number} }} <span class="badge bg-secondary">{{ ucwords(str_replace('_',' ',$document->status)) }}</span></h1><div class="text-muted">{{ $singular }} · {{ $company->name }}</div></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('sales.transactions.index',[$company,$type]) }}">Back</a>@if($document->status==='draft')<a class="btn btn-primary" href="{{ route('sales.transactions.edit',[$company,$type,$document]) }}">Edit Draft</a>@endif</div></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card p-4"><div class="row g-2 mb-4"><div class="col-md-3"><strong>Customer:</strong> {{ $document->customer->name }}</div><div class="col-md-3"><strong>Branch:</strong> {{ $document->branch->name }}</div><div class="col-md-3"><strong>Date:</strong> {{ $document->{$date}->format('d M Y') }}</div><div class="col-md-3"><strong>Currency:</strong> {{ $company->baseCurrency->code }}</div></div>
@if(method_exists($document,'lines'))<div class="table-responsive"><table class="table"><thead><tr><th>Description</th><th class="text-end">Quantity</th><th class="text-end">Unit Price</th><th class="text-end">Amount</th></tr></thead><tbody>@foreach($document->lines as $line)<tr><td>{{ $line->description }}</td><td class="text-end">{{ number_format((float)$line->quantity,2) }}</td><td class="text-end">{{ $money->format($line->unit_price,$company->baseCurrency) }}</td><td class="text-end">{{ $money->format($line->line_amount,$company->baseCurrency) }}</td></tr>@endforeach</tbody><tfoot><tr class="fw-bold"><td colspan="3" class="text-end">Total</td><td class="text-end">{{ $money->format($document->total,$company->baseCurrency) }}</td></tr></tfoot></table></div>@endif
@if($type==='receipts')<p class="fs-5"><strong>Receipt Amount:</strong> {{ $money->format($document->amount,$company->baseCurrency) }}</p><div class="table-responsive"><table class="table"><thead><tr><th>Invoice</th><th class="text-end">Allocated</th></tr></thead><tbody>@foreach($document->allocations as $allocation)<tr><td>{{ $allocation->invoice->invoice_number }}</td><td class="text-end">{{ $money->format($allocation->amount,$company->baseCurrency) }}</td></tr>@endforeach</tbody></table></div>@endif
<div class="d-flex flex-wrap gap-2 mt-3">@if($document->status==='draft' && in_array($type,['invoices','credit-notes','receipts']))<form method="post" action="{{ route('sales.transactions.post',[$company,$type,$document]) }}">@csrf<button class="btn btn-success">Post {{ $singular }}</button></form>@endif
@if($type==='quotations' && $document->status==='draft')<form method="post" action="{{ route('sales.quotations.convert',[$company,$document]) }}">@csrf<button class="btn btn-success">Convert to Sales Order</button></form>@endif
@if($type==='orders' && $document->status==='draft')<form method="post" action="{{ route('sales.orders.convert',[$company,$document]) }}" class="row g-2">@csrf<div class="col"><select name="accounting_period_id" class="form-select" required>@foreach($years as $year) @foreach($year->periods as $period)<option value="{{ $period->id }}">{{ $period->name }}</option>@endforeach @endforeach</select></div><div class="col"><input type="date" name="invoice_date" value="{{ today()->toDateString() }}" class="form-control" required></div><div class="col"><input type="date" name="due_date" value="{{ today()->addDays($document->customer->payment_terms_days)->toDateString() }}" class="form-control" required></div><div class="col"><button class="btn btn-success">Convert to Invoice</button></div></form>@endif</div>
@if($document->status==='draft')<hr><form method="post" action="{{ route('sales.transactions.destroy',[$company,$type,$document]) }}" onsubmit="return confirm('Permanently delete this Draft?')">@csrf @method('DELETE')<label class="form-label">Type <strong>{{ $document->{$number} }}</strong> to permanently delete</label><div class="d-flex gap-2"><input name="confirmation" class="form-control" style="max-width:260px" required><button class="btn btn-outline-danger">Delete Draft</button></div></form>@endif</div>
@endsection
