@extends('layouts.app')
@section('content')
<h1 class="mb-4">Accounting Reports</h1>
<div class="card p-4">
<form method="get" class="row g-3">
    <div class="col-lg-4"><label class="form-label">Company</label><select id="report-company" name="company_id" class="form-select" onchange="filterAccounts()">@foreach($companies as $c)<option value="{{ $c->id }}" @selected(request('company_id')==$c->id)>{{ $c->name }}</option>@endforeach</select></div>
    <div class="col-lg-4"><label class="form-label">Branch</label><select id="report-branch" name="branch_id" class="form-select"><option value="">All branches (consolidated)</option>@foreach($companies as $c) @foreach($c->branches as $branch)<option data-company="{{ $c->id }}" value="{{ $branch->id }}" @selected(request('branch_id')==$branch->id)>{{ $branch->code }} — {{ $branch->name }}</option>@endforeach @endforeach</select></div>
    <div class="col-lg-4"><label class="form-label">Financial Year</label><select id="report-year" name="financial_year_id" class="form-select"><option value="">All Financial Years</option>@foreach($companies as $c) @foreach($c->financialYears as $year)<option data-company="{{ $c->id }}" value="{{ $year->id }}" @selected(request('financial_year_id')==$year->id)>{{ $year->name }} ({{ ucfirst($year->status) }})</option>@endforeach @endforeach</select></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">From</label><input type="date" name="from" value="{{ request('from') }}" class="form-control"></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">To</label><input type="date" name="to" value="{{ request('to') }}" class="form-control"></div>
    <div class="col-lg-4"><label class="form-label">Account (General Ledger)</label><select id="report-account" name="account_id" class="form-select">@foreach($companies as $c) @foreach($c->accounts as $a)<option data-company="{{ $c->id }}" value="{{ $a->id }}" @selected(request('account_id')==$a->id)>{{ $a->code }} — {{ $a->name }}</option>@endforeach @endforeach</select></div>
    <div class="col-12 d-flex gap-2 flex-wrap pt-2"><button formaction="{{ route('reports.ledger') }}" class="btn btn-primary">General Ledger</button><button formaction="{{ route('reports.trial') }}" class="btn btn-primary">Trial Balance</button><button formaction="{{ route('reports.profit-loss') }}" class="btn btn-primary">Profit & Loss</button><button formaction="{{ route('reports.balance-sheet') }}" class="btn btn-primary">Balance Sheet</button></div>
</form></div>
<script>function filterAccounts(){const company=document.querySelector('#report-company').value,select=document.querySelector('#report-account'),branch=document.querySelector('#report-branch');branch.querySelectorAll('option[data-company]').forEach(option=>option.hidden=option.dataset.company!==company);if(branch.selectedOptions[0]?.hidden)branch.value='';let first=null,current=select.value;select.querySelectorAll('option').forEach(option=>{option.hidden=option.dataset.company!==company;if(!option.hidden&&!first)first=option});if(!select.querySelector('option[value="'+current+'"]:not([hidden])')&&first)select.value=first.value}filterAccounts()</script>
@endsection
