@php
    $existingLines = old('lines', $journal?->lines?->map(fn ($line) => ['account_id' => $line->account_id, 'description' => $line->description, 'debit' => number_format((float) $line->debit, 2, '.', ''), 'credit' => number_format((float) $line->credit, 2, '.', '')])->all() ?? [['account_id' => '', 'description' => '', 'debit' => '0.00', 'credit' => '0.00'], ['account_id' => '', 'description' => '', 'debit' => '0.00', 'credit' => '0.00']]);
    $attemptedDate = old('transaction_date');
    $blockedYear = $attemptedDate ? $years->first(fn ($year) => $attemptedDate >= $year->starts_on->toDateString() && $attemptedDate <= $year->ends_on->toDateString() && in_array($year->status, ['closed', 'filed'])) : null;
    $journalYearContext = $years->map(fn ($year) => [
        'id' => $year->id,
        'name' => $year->name,
        'status' => $year->status,
        'starts_on' => $year->starts_on->toDateString(),
        'ends_on' => $year->ends_on->toDateString(),
        'periods' => $year->periods->map(fn ($period) => [
            'id' => $period->id,
            'name' => $period->name,
            'status' => $period->status,
            'starts_on' => $period->starts_on->toDateString(),
            'ends_on' => $period->ends_on->toDateString(),
        ])->values(),
    ])->values();
@endphp
@if($errors->any())<div class="alert alert-danger"><strong>Please correct the journal.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($blockedYear)<div class="mb-3"><a class="btn btn-outline-primary" href="{{ route('companies.prior-adjustments.create', [$company, 'origin_financial_year_id' => $blockedYear->id]) }}">Create Prior-Period Adjustment</a></div>@endif
<form method="post" action="{{ $action }}" class="card p-4">@csrf @if($method === 'PUT') @method('PUT') @endif
<div class="text-muted mb-3">Base currency: {{ $company->baseCurrency?->code ?? '' }}</div>
<div id="journal-period-context" class="alert alert-info">Financial Year and Accounting Period will be resolved from the Journal Date.</div>
<div class="row g-3"><div class="col-md-4"><label class="form-label">Branch</label><select name="branch_id" class="form-select" required><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) old('branch_id', $journal?->branch_id ?? ($branches->count() === 1 ? $branch->id : '')) === (string) $branch->id)>{{ $branch->code }} — {{ $branch->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Financial Year</label><select name="financial_year_id" class="form-select">@foreach($years as $year)<option value="{{ $year->id }}" @selected(old('financial_year_id', $journal?->financial_year_id) == $year->id)>{{ $year->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Accounting Period</label><select name="accounting_period_id" class="form-select">@foreach($years as $year) @foreach($year->periods as $period)<option value="{{ $period->id }}" @selected(old('accounting_period_id', $journal?->accounting_period_id) == $period->id)>{{ $period->name }} ({{ ucfirst($period->status) }})</option>@endforeach @endforeach</select></div><div class="col-md-4"><label class="form-label">Journal Date</label><input type="date" name="transaction_date" value="{{ old('transaction_date', $journal?->transaction_date?->toDateString()) }}" class="form-control" required></div><div class="col-md-4"><label class="form-label">Reference</label><input name="reference" value="{{ old('reference', $journal?->reference) }}" class="form-control"></div><div class="col-md-8"><label class="form-label">Description / Narration</label><input name="description" value="{{ old('description', $journal?->description) }}" class="form-control" required></div></div>
<h5 class="mt-4">Journal Lines</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th style="min-width:220px">Account</th><th style="min-width:180px">Description</th><th style="min-width:130px">Debit</th><th style="min-width:130px">Credit</th><th>Action</th></tr></thead><tbody id="journal-lines">@foreach($existingLines as $index => $line)<tr class="journal-line"><td><select name="lines[{{ $index }}][account_id]" class="form-select" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($line['account_id'] ?? '') == $account->id)>{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></td><td><input name="lines[{{ $index }}][description]" value="{{ $line['description'] ?? '' }}" class="form-control"></td><td><input name="lines[{{ $index }}][debit]" value="{{ $line['debit'] ?? '0.00' }}" type="number" min="0" step="0.01" class="form-control" aria-label="Debit"></td><td><input name="lines[{{ $index }}][credit]" value="{{ $line['credit'] ?? '0.00' }}" type="number" min="0" step="0.01" class="form-control" aria-label="Credit"></td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeLine(this)">Remove Line</button></td></tr>@endforeach</tbody></table></div>
<div class="d-flex gap-2"><button type="button" class="btn btn-outline-secondary" onclick="addLine()">Add Line</button><button class="btn btn-primary">{{ $journal ? 'Update Draft' : 'Save Draft' }}</button><a class="btn btn-outline-secondary" href="{{ $journal ? route('journals.show', [$company, $journal]) : route('accounting', ['company_id' => $company->id]) }}">Cancel</a></div></form>
<template id="journal-line-template"><tr class="journal-line"><td><select class="form-select account" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></td><td><input class="form-control description"></td><td><input value="0.00" type="number" min="0" step="0.01" class="form-control debit" aria-label="Debit"></td><td><input value="0.00" type="number" min="0" step="0.01" class="form-control credit" aria-label="Credit"></td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="removeLine(this)">Remove Line</button></td></tr></template>
<script>let lineIndex={{ count($existingLines) }};function addLine(){const row=document.querySelector('#journal-line-template').content.cloneNode(true);row.querySelector('.account').name=`lines[${lineIndex}][account_id]`;row.querySelector('.description').name=`lines[${lineIndex}][description]`;row.querySelector('.debit').name=`lines[${lineIndex}][debit]`;row.querySelector('.credit').name=`lines[${lineIndex}][credit]`;document.querySelector('#journal-lines').append(row);lineIndex++}function removeLine(button){button.closest('tr').remove()}</script>
<script>const journalYears=@json($journalYearContext),journalYear=document.querySelector('[name="financial_year_id"]'),journalPeriod=document.querySelector('[name="accounting_period_id"]'),journalDate=document.querySelector('[name="transaction_date"]');if(!journalYear.querySelector('option[value=""]'))journalYear.insertAdjacentHTML('afterbegin','<option value="">Resolve from Journal Date</option>');if(!journalPeriod.querySelector('option[value=""]'))journalPeriod.insertAdjacentHTML('afterbegin','<option value="">Resolve from Journal Date</option>');function resolveJournalPeriod(){const date=journalDate.value,box=document.querySelector('#journal-period-context');if(!date)return;const matches=journalYears.filter(year=>date>=year.starts_on&&date<=year.ends_on);if(matches.length!==1){box.className='alert alert-danger';box.textContent='No unique Financial Year exists for '+date+'.';return}const year=matches[0],period=year.periods.find(item=>date>=item.starts_on&&date<=item.ends_on);box.className='alert '+(year.status==='open'&&period?.status==='open'?'alert-info':'alert-warning');box.textContent='Resolved context: Financial Year '+year.name+' ('+year.status+') · Accounting Period '+(period?period.name+' ('+period.status+')':'not configured')}journalDate.addEventListener('change',()=>{journalYear.value='';journalPeriod.value='';resolveJournalPeriod()});resolveJournalPeriod()</script>
