@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1>Create Prior-Period Adjustment</h1><div class="text-muted">{{ $company->entity_label }}</div></div><a class="btn btn-outline-secondary" href="{{ route('companies.financial-years.index', $company) }}">Cancel</a></div>
<div class="alert alert-warning"><strong>No automatic posting:</strong> this creates a controlled Draft adjustment record only. It does not change the original transaction date, reopen a year, or create a journal.</div>
<form class="card p-4" method="post" action="{{ route('companies.prior-adjustments.store', $company) }}">@csrf
    <input type="hidden" name="origin_financial_year_id" value="{{ $origin->id }}">
    <div class="row g-3"><div class="col-md-6"><label class="form-label">Origin Financial Year</label><input class="form-control" value="{{ $origin->name }} ({{ ucfirst($origin->status) }})" readonly></div><div class="col-md-6"><label class="form-label">Adjustment Financial Year</label><select name="adjustment_financial_year_id" class="form-select" required><option value="">Select open year</option>@foreach($adjustmentYears as $year)<option value="{{ $year->id }}">{{ $year->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Adjustment Type</label><select name="adjustment_type" class="form-select" required><option value="accounting_correction">Accounting correction</option><option value="source_document_omission">Source document omission</option><option value="opening_balance_correction">Opening balance correction</option><option value="other">Other</option></select></div><div class="col-md-6"><label class="form-label">Source Document / Reference</label><input name="source_reference" class="form-control" value="{{ old('source_reference') }}" placeholder="Invoice, receipt or external reference"></div><div class="col-12"><label class="form-label">Reason</label><textarea name="reason" class="form-control" rows="4" minlength="10" required>{{ old('reason') }}</textarea></div></div>
    <div class="mt-4"><button class="btn btn-primary" @disabled($adjustmentYears->isEmpty())>Create Draft Adjustment</button>@if($adjustmentYears->isEmpty())<span class="text-danger ms-2">No open adjustment Financial Year is available.</span>@endif</div>
</form>
@endsection
