@extends('layouts.app')
@section('content')
<h1>Edit Customer</h1><p class="text-muted">{{ $company->name }}</p>
<div class="card p-4"><form method="post" action="{{ route('sales.customers.update',[$company,$customer]) }}" class="row g-3">@csrf @method('PUT')
@foreach(['code'=>'Customer Code','name'=>'Customer Name','legal_name'=>'Legal / Business Name','email'=>'Email','phone'=>'Phone'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ $field }}" value="{{ old($field,$customer->{$field}) }}" @required(in_array($field,['code','name']))></div>@endforeach
<div class="col-md-6"><label class="form-label">Customer Type</label><select class="form-select" name="type"><option value="business" @selected($customer->type==='business')>Business</option><option value="individual" @selected($customer->type==='individual')>Individual</option></select></div>
<div class="col-md-6"><label class="form-label">Billing Address</label><textarea class="form-control" name="billing_address">{{ old('billing_address',$customer->billing_address) }}</textarea></div><div class="col-md-6"><label class="form-label">Shipping Address</label><textarea class="form-control" name="shipping_address">{{ old('shipping_address',$customer->shipping_address) }}</textarea></div>
<div class="col-md-4"><label class="form-label">Payment Terms (Days)</label><input type="number" min="0" class="form-control" name="payment_terms_days" value="{{ old('payment_terms_days',$customer->payment_terms_days) }}"></div><div class="col-md-4"><label class="form-label">Credit Limit ({{ $money->label($company->baseCurrency) }})</label><input type="number" min="0" step="0.01" class="form-control" name="credit_limit" value="{{ old('credit_limit',$customer->credit_limit) }}"></div><div class="col-md-4"><label class="form-label">Receivable Account</label><select class="form-select" name="receivable_account_id">@foreach($company->accounts()->where('type','asset')->get() as $a)<option value="{{ $a->id }}" @selected($customer->receivable_account_id===$a->id)>{{ $a->code }} — {{ $a->name }}</option>@endforeach</select></div>
<input type="hidden" name="currency_id" value="{{ $customer->currency_id }}"><div class="col-12"><a class="btn btn-secondary" href="{{ route('sales.customers',$company) }}">Cancel</a><button class="btn btn-primary">Save Changes</button></div></form></div>
@if(!$deletable)<div class="alert alert-info mt-4">This customer has transactional history and cannot be permanently deleted. Deactivate it if it should no longer be used.</div>@endif
@endsection
