@extends('layouts.app')
@section('content')
<h1>Customers — {{ $company->name }}</h1>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card p-4 mb-4"><h2 class="h5 mb-3">Add Customer</h2><form method="post" action="{{ route('sales.customers.store',$company) }}" class="row g-3">@csrf
<div class="col-md-4"><label class="form-label">Customer Code</label><input class="form-control" name="code" placeholder="Generated if blank"></div>
<div class="col-md-8"><label class="form-label">Customer Name</label><input class="form-control" name="name" required></div>
<div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control" name="email"></div>
<div class="col-md-6"><label class="form-label">Receivable Account</label><select class="form-select" name="receivable_account_id">@foreach($company->accounts()->where('type','asset')->get() as $a)<option value="{{ $a->id }}" @selected($a->code==='1100')>{{ $a->code }} — {{ $a->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Payment Terms (Days)</label><input type="number" min="0" name="payment_terms_days" value="30" class="form-control" required></div>
<div class="col-md-4"><label class="form-label">Credit Limit ({{ $money->label($company->baseCurrency) }})</label><div class="input-group"><span class="input-group-text">{{ $money->symbol($company->baseCurrency) }}</span><input type="number" min="0" name="credit_limit" value="0.00" step="0.01" class="form-control" required></div></div>
<input type="hidden" name="currency_id" value="{{ $company->base_currency_id }}"><div class="col-md-4 d-flex align-items-end"><button class="btn btn-primary w-100">Add Customer</button></div></form></div>
<div class="table-responsive card"><table class="table table-hover align-middle mb-0"><thead><tr><th>Code</th><th>Name</th><th>Email</th><th>Credit Limit</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($customers as $customer)<tr><td>{{ $customer->code }}</td><td>{{ $customer->name }}</td><td>{{ $customer->email ?: '—' }}</td><td>{{ $money->format($customer->credit_limit,$company->baseCurrency) }}</td><td><span class="badge {{ $customer->is_active?'bg-success':'bg-secondary' }}">{{ $customer->is_active?'Active':'Inactive' }}</span></td><td><div class="d-flex flex-wrap gap-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('sales.customers.edit',[$company,$customer]) }}">Edit</a><form method="post" action="{{ route('sales.customers.status',[$company,$customer]) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $customer->is_active?0:1 }}"><button class="btn btn-sm btn-outline-secondary">{{ $customer->is_active?'Deactivate':'Reactivate' }}</button></form>@if($deletable[$customer->id])<a class="btn btn-sm btn-outline-danger" href="{{ route('sales.customers.delete',[$company,$customer]) }}">Delete</a>@endif</div></td></tr>@endforeach</tbody></table></div>
@endsection
