@extends('layouts.app')
@section('content')
<h1>Edit Tax Registration</h1>
<p class="text-muted">{{$company->entity_label}} · {{$company->country->name}}</p>
<form class="card p-4" method="post" action="{{route('tax.registrations.update',[$company->country->code,$company,$registration])}}">@csrf @method('PUT')
<div class="row g-3">@foreach(['name'=>'Name','registration_number'=>'Registration Number','registration_name'=>'Registration Name'] as $field=>$label)<div class="col-md-4"><label class="form-label">{{$label}}</label><input class="form-control" name="{{$field}}" value="{{old($field,$registration->{$field})}}" required></div>@endforeach
<div class="col-md-3"><label class="form-label">Tax Type</label><select class="form-select" name="tax_type">@foreach(['GST','VAT','Sales Tax','Other Indirect Tax'] as $value)<option @selected(old('tax_type',$registration->tax_type)===$value)>{{$value}}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Effective From</label><input class="form-control" type="date" name="effective_from" value="{{old('effective_from',$registration->effective_from?->toDateString())}}" required></div><div class="col-md-3"><label class="form-label">Effective To</label><input class="form-control" type="date" name="effective_to" value="{{old('effective_to',$registration->effective_to?->toDateString())}}"></div>
<div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(['draft','active','inactive','cancelled'] as $value)<option value="{{$value}}" @selected(old('status',$registration->status)===$value)>{{ucfirst($value)}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Filing Frequency</label><select class="form-select" name="filing_frequency">@foreach(['monthly','two_monthly','quarterly','six_monthly','annual','other'] as $value)<option value="{{$value}}" @selected(old('filing_frequency',$registration->filing_frequency)===$value)>{{str($value)->replace('_',' ')->title()}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Accounting Basis</label><select class="form-select" name="accounting_basis">@foreach(['accrual','cash'] as $value)<option value="{{$value}}" @selected(old('accounting_basis',$registration->accounting_basis)===$value)>{{ucfirst($value)}}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes">{{old('notes',$registration->notes)}}</textarea></div></div>
<div class="d-flex gap-2 mt-3"><button class="btn btn-primary">Update Registration</button><a class="btn btn-outline-secondary" href="{{route('tax.workspace',[$company->country->code,$company])}}">Cancel</a></div></form>
@endsection
