@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <div><h1 class="mb-1">Financial Years</h1><div class="text-muted">{{ $company->entity_label }} · {{ ucfirst(str_replace('_', ' ', $company->entity_type)) }}</div></div>
    <a href="{{ route('companies.show', $company) }}" class="btn btn-outline-secondary">Back to Entity</a>
</div>
<div class="card p-4 mb-4">
    <h5>Add Financial Year</h5>
    <p class="text-muted">Financial Years for the same entity cannot overlap. Monthly Accounting Periods are created automatically.</p>
    <form method="post" action="{{ route('companies.financial-years.store', $company) }}">@csrf
        <div class="row g-3"><div class="col-md-4"><label class="form-label">Year label</label><input name="name" class="form-control" placeholder="2026–2027" required></div><div class="col-md-3"><label class="form-label">Start date</label><input type="date" name="starts_on" class="form-control" required></div><div class="col-md-3"><label class="form-label">End date</label><input type="date" name="ends_on" class="form-control" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">Add Year</button></div></div>
    </form>
</div>
@forelse($years as $year)
<div class="card mb-4">
    <div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2">
        <div><strong class="fs-5">{{ $year->name }}</strong><span class="text-muted ms-2">{{ $year->starts_on->format('d M Y') }} – {{ $year->ends_on->format('d M Y') }}</span></div>
        <div class="d-flex gap-2"><span class="badge text-bg-{{ $year->isCurrent() ? 'info' : ($year->isFuture() ? 'light' : 'dark') }}">{{ ucfirst($year->datePosition()) }} Year</span><span class="badge text-bg-{{ $year->status === 'open' ? 'success' : ($year->status === 'closing' ? 'warning' : ($year->status === 'filed' ? 'primary' : 'secondary')) }}">{{ ucfirst($year->status) }}</span></div>
    </div>
    <div class="card-body">
        @if($year->status === 'closing')<div class="alert alert-warning">This year is in controlled finalisation. Normal posting is blocked until it is reopened or fully closed.</div>@elseif($year->status === 'closed')<div class="alert alert-secondary">Ordinary posting is blocked. Reopening requires an explicit reason and confirmation.</div>@elseif($year->status === 'filed')<div class="alert alert-primary">This year is Filed and cannot be reopened through the normal workflow. Use a Prior-Period Adjustment.</div>@endif
        <h6>Accounting Periods</h6>
        <div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Period</th><th>Start</th><th>End</th><th>Status</th><th class="text-end">Controlled Action</th></tr></thead><tbody>
        @foreach($year->periods as $period)<tr><td>{{ $period->name }}</td><td>{{ $period->starts_on->format('d M Y') }}</td><td>{{ $period->ends_on->format('d M Y') }}</td><td><span class="badge text-bg-{{ $period->status === 'open' ? 'success' : 'secondary' }}">{{ ucfirst($period->status) }}</span></td><td class="text-end">
            @if($year->status === 'open' && $period->status === 'open' && !$period->ends_on->isAfter(today()))<details class="d-inline-block text-start"><summary class="btn btn-sm btn-outline-warning">Close Period</summary><form method="post" action="{{ route('companies.financial-years.periods.close', [$company, $year, $period]) }}" class="border rounded p-2 mt-2" style="min-width:300px">@csrf<label class="form-label">Reason</label><input name="reason" class="form-control form-control-sm mb-2" required minlength="10"><label class="form-label">Type CLOSE PERIOD</label><input name="confirmation" class="form-control form-control-sm mb-2" required><button class="btn btn-sm btn-warning">Confirm Close</button></form></details>
            @elseif($year->status === 'open' && $period->status === 'open')<span class="text-muted">Not yet eligible</span>
            @elseif($year->status === 'open' && $period->status === 'closed')<details class="d-inline-block text-start"><summary class="btn btn-sm btn-outline-danger">Reopen Period</summary><form method="post" action="{{ route('companies.financial-years.periods.reopen', [$company, $year, $period]) }}" class="border rounded p-2 mt-2" style="min-width:300px">@csrf<label class="form-label">Authorised reason</label><input name="reason" class="form-control form-control-sm mb-2" required minlength="10"><label class="form-label">Type REOPEN PERIOD</label><input name="confirmation" class="form-control form-control-sm mb-2" required><button class="btn btn-sm btn-danger">Confirm Reopen</button></form></details>
            @else<span class="text-muted">Unavailable while year is {{ ucfirst($year->status) }}</span>@endif
        </td></tr>@endforeach
        </tbody></table></div>
        <div class="border-top pt-3 mt-3 d-flex flex-wrap gap-3 align-items-start">
            @if($year->status === 'open' && $year->isPast() && !$year->periods->contains(fn ($period) => $period->status !== 'closed'))<details><summary class="btn btn-warning">Begin Financial Year Closing</summary><form method="post" action="{{ route('companies.financial-years.begin-closing', [$company, $year]) }}" class="border rounded p-3 mt-2" style="min-width:360px">@csrf<label class="form-label">Finalisation reason</label><input name="reason" class="form-control mb-2" required minlength="10"><label class="form-label">Type BEGIN CLOSING</label><input name="confirmation" class="form-control mb-2" required><button class="btn btn-warning">Enter Closing</button></form></details>
            @elseif($year->status === 'open' && $year->isPast())<span class="text-muted">Close all Accounting Periods before Financial Year closing can begin.</span>
            @elseif($year->status === 'closing')@if($year->isPast())<details><summary class="btn btn-danger">Complete Financial Year Close</summary><form method="post" action="{{ route('companies.financial-years.close', [$company, $year]) }}" class="border rounded p-3 mt-2" style="min-width:360px">@csrf<label class="form-label">Final close reason</label><input name="reason" class="form-control mb-2" required minlength="10"><label class="form-label">Type CLOSE YEAR</label><input name="confirmation" class="form-control mb-2" required><button class="btn btn-danger">Complete Financial Year Close</button></form></details>@endif<details><summary class="btn btn-outline-secondary">Cancel Financial Year Closing</summary><form method="post" action="{{ route('companies.financial-years.cancel-closing', [$company, $year]) }}" class="border rounded p-3 mt-2" style="min-width:360px">@csrf<label class="form-label">Reason</label><input name="reason" class="form-control mb-2" required minlength="10"><label class="form-label">Type CANCEL CLOSING</label><input name="confirmation" class="form-control mb-2" required><button class="btn btn-outline-secondary">Cancel Financial Year Closing</button></form></details>
            @elseif($year->status === 'closed')<details><summary class="btn btn-outline-danger">Authorised Reopen</summary><form method="post" action="{{ route('companies.financial-years.reopen', [$company, $year]) }}" class="border rounded p-3 mt-2" style="min-width:360px">@csrf<label class="form-label">Authorised reason</label><input name="reason" class="form-control mb-2" required minlength="10"><label class="form-label">Type REOPEN YEAR</label><input name="confirmation" class="form-control mb-2" required><button class="btn btn-danger">Reopen Year</button></form></details>@if($year->isPast())<details><summary class="btn btn-outline-primary">Mark Filed</summary><form method="post" action="{{ route('companies.financial-years.file', [$company, $year]) }}" class="border rounded p-3 mt-2" style="min-width:360px">@csrf<label class="form-label">Filing reference</label><input name="reference" class="form-control mb-2" required><label class="form-label">Type MARK FILED</label><input name="confirmation" class="form-control mb-2" required><button class="btn btn-primary">Mark Filed</button></form></details>@endif<a class="btn btn-outline-primary" href="{{ route('companies.prior-adjustments.create', [$company, 'origin_financial_year_id' => $year->id]) }}">Create Prior-Period Adjustment</a>
            @elseif($year->status === 'filed')<a class="btn btn-primary" href="{{ route('companies.prior-adjustments.create', [$company, 'origin_financial_year_id' => $year->id]) }}">Create Prior-Period Adjustment</a>@endif
        </div>
    </div>
</div>
@empty<div class="alert alert-warning">No Financial Years configured.</div>@endforelse
@endsection
